### ISSUE TITLE
[Bug]Incorrect description on Dark Theme Inline Title Custom Text Color

### ISSUE THREAD

**Issue by ZephiraZ** [damiankorcz/Prism-Theme#100]
**Describe the bug**
The description for the "Inline Title Custom Text Color" option in Style Settings indicates "Light Theme" in the Dark Theme section.

**To Reproduce**
1. Open Style Settings.
2. Click on Prism Theme > Editor > Headers > Header Text Color > Dark Theme.
3. The description of "Inline Title Custom Text Color" states "Make sure you selected 'Custom' in Light Theme..."

**Expected behavior**
As this is the Dark Theme section, it is expected that this description would state "Dark Theme" instead of "Light Theme".

**Screenshots**
![InlineTitleCustomTextColorDescription](https://user-images.githubusercontent.com/102687150/203442938-0abafc4d-6c10-4a5a-ae4c-933ddf86165e.png)

**Setup Information**
 - Device Type: Lenovo laptop
 - Operating System: Windows 10
 - Prism version: 3.0.4
 - Color Schemes Used: Raven
 - Obsidian Version: v1.0.3
 - Obsidian Installer Version: v0.15.9
 - Related Community plugins: Style Settings

**Additional context**
Issue was not observed for other items in this specific section.

**Comment by damiankorcz** [comment]
Hi @ZephiraZ,
Good catch! Thanks for reporting. I'll have it fixed for the next patch release.

**Comment by damiankorcz** [comment]
Hi @ZephiraZ,
This issue should now be addressed in version 3.1.0.
