### ISSUE TITLE
Db folder plugin: global search and filters hidden

### ISSUE THREAD

**Issue by giancarlocella** [damiankorcz/Prism-Theme#103]
The global search and filters row of a db folder table is hidden. It seems that it is below the top header.
This is how a table appears with the standard theme:

![image](https://user-images.githubusercontent.com/6838194/205699048-1d6877be-e4ca-49b8-9756-13d2e91f1ee2.png)

The same with the Prism theme:

![image](https://user-images.githubusercontent.com/6838194/205699211-645f3d58-c90f-4217-b1a9-d72ab4c64e71.png)

**Comment by damiankorcz** [comment]
Hi @giancarlocella,
This is a related issue to #100 and will be addressed in a coming update. Thanks for reporting!

**Comment by damiankorcz** [comment]
Hi @giancarlocella,
This issue should now be addressed in version 3.1.0.
