### ISSUE TITLE
[Bug] Collapse left sidebar button too high

### ISSUE THREAD

**Issue by bb** [damiankorcz/Prism-Theme#104]
**Describe the bug**

The Toolbar button "Collapse left sidebar" is too high on macOS when Appearance→Advanced→Window Frame Style "Hidden (default)" is selected.
Also, it should be on the left, but it's on the right. See screenshot.

It's fine when using another window frame style and also fine in full screen.

**To Reproduce**
1. Open Obsidian on macOS Ventura
2. Ensure you're not in full screen mode
3. In Settings → Appearance → Advanced → Window frame style, ensure "Hidden (default)" is selected
5. Add icons like Folders, Favorites, Search, Recent (or similar) to the toolbar)
6. Compare height of the toolbar items, for me **"Collapse left sidebar" is too high**.

**Expected behavior**

All toolbar items should have the same height

**Screenshots**

![](https://user-images.githubusercontent.com/4932/206809348-4c41fd07-ec02-4aa2-b67a-b5a3e10eed16.png)

**Setup Information**
 - Device Type: MacBook Pro 16"
 - Operating System: macOS Ventura 13.0.1
 - Prism version: 3.1.0
 - Color Schemes Used: Accent: rgb(139,108,239), Light/Dark: Adapt to System (Both light and dark are affected)
 - Obsidian Version: 1.0.3
 - Obsidian Installer Version: 1.0.3
 - Related Community plugins: Style Settings, and more, seems unrelated

**Comment by damiankorcz** [comment]
Hi @bb,
This should now be addressed in Prism 3.1.1. Also, the button by default is on the right when the sidebar is expanded but I've fixed the alignment to match the default theme now.

I have a way to test on macOS now so if you encounter any other issues let me know!
Thanks for reporting.

**Comment by bb** [comment]
The height of the button is fixed for me, thank you!
