### ISSUE TITLE
[Bug] Some feature Obsidian Projects Plugin is not shown with prism theme

### ISSUE THREAD

**Issue by dwywdo** [damiankorcz/Prism-Theme#105]
**Describe the bug**
`Projects`, One of recent useful obsidian plugin provides obsidian note management based on different view, just like notion
I'm interested in this plugin and it seems to be quiet good. However, when I use this plugin with sanctum theme, 
I don't see the some of buttons that creates views from projects

**To Reproduce**
1. Use Prism as theme of obsidian
2. Install & Enable obsidian projects plugin (Command = Projects: Create a new note)
3. Create a new project and see (Command = Projects: Show Projects

**Expected behavior**
When there's no theme is applied, there are buttons for created projects (`Schedule`), Filter, New button
![Screen Shot 2022-12-21 at 10 30 02 AM](https://user-images.githubusercontent.com/43313941/208799231-3f512a1d-ab51-4ed1-ba28-2a832804acca.png)

**Screenshots**
When Prism theme is applied, above menus are missing
![Screen Shot 2022-12-21 at 10 29 27 AM](https://user-images.githubusercontent.com/43313941/208799153-daa1c568-7fcf-48ae-9437-ba8cba8a04cc.png)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS BigSur
 - Prism version: Prism 3.0.3
 - Color Schemes Used: Swan
 - Obsidian Version: v1.0.3
 - Obsidian Installer Version: v0.15.9
 - Related Community plugins: Projects (https://github.com/marcusolsson/obsidian-projects)

**Additional context**
[Add any other context about the problem here]

**Comment by damiankorcz** [comment]
Hi @dwywdo,
This was fixed in Prism 3.1.0. Please update the theme and let me know if it resolves your issue. Thanks.

**Comment by dwywdo** [comment]
Oh I've should checked by updating first..! 😅 Thanks for quick response! I've confirmed that it works well now 🙇 
![Screen Shot 2022-12-21 at 10 38 23 AM](https://user-images.githubusercontent.com/43313941/208800137-491749dc-5b40-4011-b2ed-7df00902d0f1.png)
Let me close this issue!
