### ISSUE TITLE
[Bug] The new color schemes are too dark

### ISSUE THREAD

**Issue by lsvy97** [damiankorcz/Prism-Theme#106]
**Is your feature request related to a problem? Please describe.**
After the 3.0 update dark color schemes the background is darker than it was earlier and the interface text lacks the needed contrast.

**Describe the solution you'd like**
Old colorschemes were really good, would be nice to bring them back.

**Describe alternatives you've considered**
I considered editing the background colors myself, but the css is too big, and I can't figure it out. Also all the colors seem to be the same?

**Additional context**
Here are the screenshots of Prism 2.x and 3.x. I think it's not just the layout, the background colors are definitely different.

![Snipaste_2022-12-28_15-30-25](https://user-images.githubusercontent.com/32693465/209783169-f8e54e15-f6dc-4aa6-9392-88886f143db2.png)
![Snipaste_2022-12-28_15-30-09](https://user-images.githubusercontent.com/32693465/209783176-30f61d52-81d4-49d8-a6bc-361518c6dd9c.png)

**Comment by damiankorcz** [comment]
Hi @lsvy97,
The layout changes are how they should be since Prism 3.0.0 was rewritten from scratch to accommodate the changes made to the default theme when Obsidian 1.0.0 released. This brought along a change in style to the current more simplistic one.

As for the colours and contrast, I do agree that the current dark themes are a little too dark and I do intend on working on it in the new year. Probably will be the next major update. Thanks for reporting!

**Comment by lsvy97** [comment]
Good to know! Keep up the great work! 👍

**Comment by damiankorcz** [comment]
Hi @lsvy97,
I've completely reworked the colour schemes in the new Prism 3.3.0 update. Should be a lot better for Dark Colour Schemes. Not exactly as grey as before though. If you want you can make your own Colour Scheme by following this guide: https://github.com/damiankorcz/Prism-Theme/wiki/Creating-a-Custom-Colour-Scheme-CSS-Snippet

**Comment by lsvy97** [comment]
Thank you. For curiosity, I checked it with a colorpicker and the color is literally the same now.
![image](https://github.com/damiankorcz/Prism-Theme/assets/32693465/06416759-61d1-425e-8fd6-8005c7c57cdd)
![image](https://github.com/damiankorcz/Prism-Theme/assets/32693465/0627e890-9471-4fd0-adb8-d62a50c66fcd)
