### ISSUE TITLE
[Bug] Uncentered Search Bar in Small Canvas Cards

### ISSUE THREAD

**Issue by isdmg** [damiankorcz/Prism-Theme#107]
**Describe the bug**
The search bar in a canvas card is not centered, unlike in the default theme.

**To Reproduce**
1. Create a canvas
2. Create a card
3. Click the card
4. Ctrl + F to open the search bar

**Expected behavior**
The default theme:
![image](https://user-images.githubusercontent.com/87226513/209918253-7450f58a-0bf8-4e20-91fc-2f1c426d2575.png)

**Screenshots**
Prism:
![image](https://user-images.githubusercontent.com/87226513/209918315-8c7f3ab4-daa4-44fc-9acd-f6654eb646cc.png)

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 11
 - Prism version: 3.1.1
 - Color Schemes Used: Latte
 - Obsidian Version: 1.1.9
 - Obsidian Installer Version: 0.15.9

**Comment by damiankorcz** [comment]
This issue should now be addressed in version 3.2.0.
