### ISSUE TITLE
[bug] relationship lines slightly to the right when using outline plugin compared to the default theme

### ISSUE THREAD

**Issue by imeed166** [damiankorcz/Prism-Theme#11]
![image](https://user-images.githubusercontent.com/38974541/140924363-3bf5f965-5454-46dd-822c-dea8ea56b491.png)

![image](https://user-images.githubusercontent.com/38974541/140924424-8fa27d5b-e15c-4e69-9a45-95b8948cf42f.png)

**Comment by damiankorcz** [comment]
Hi @imeed166, I'm just looking at this issue and I don't seem to see any relationship lines rendered when using the https://github.com/vslinko/obsidian-outliner plugin. Could it be that it no longer has them?

**Comment by imeed166** [comment]
It does, you just have to enable this setting
![image](https://user-images.githubusercontent.com/38974541/151048534-b2a74bf5-c0c3-4033-b987-dfc538fc1016.png)

But after a while I stopped disabled this setting, I'm using [indentation guides](https://github.com/mgmeyers/obsidian-indentation-guides) plugin which has an option in style setting for adjusting the position of the lines. I don't know if I should close this issue or not.

**Comment by damiankorcz** [comment]
Keep it open for now since I don't think for some reason they are rendering at all in the theme. If I figure it our or give up on it I'll close it. Thanks for getting back to me anyway!
