### ISSUE TITLE
Render issue with Full Calendar Plugin by davish and Prism Theme Enabled.

### ISSUE THREAD

**Issue by Jackenheimer** [damiankorcz/Prism-Theme#119]
I am having an issue maybe the Prism Theme needs to be brought into compatibility with Full Calendar Plugin by davish.

I have the required plugins installed for the Prism theme and it works great with Obsidian.

The problem I am having is that it does not play nice with Full Calendar Plugin by davish [https://github.com/davish/obsidian-full-calendar](url). 

When both plugins are enabled the top portion of the calendar is behind an opaque banner and I can not access the buttons at the top of the Full Calendar Plugin.

With Full Calendar and Prism Theme enabled. 
![With Full Calendar and Prism Enabled](https://user-images.githubusercontent.com/88523511/214473366-044e53e9-9e51-4af9-8749-db9162b1af1a.png)

With Full Calendar Enabled and Prism Theme disabled. 
![With Full Calendar and Prism Disabled](https://user-images.githubusercontent.com/88523511/214473511-972e8521-7f69-4962-9288-e3385f82da65.png)

I would like to use both plugins together if that is at all possible. Thanks for the great Theme!!!

**Comment by damiankorcz** [comment]
Hi @Jackenheimer,
Can you make sure you are on the latest version of Prism? Should be 3.2.0.

**Comment by Jackenheimer** [comment]
Just updated the theme to 3.2.0 and it is working as intended now 🙌 Did you add compatibility for Full Calendar Plugin or did  the newer version already fix these issues?

**Comment by damiankorcz** [comment]
Hi @Jackenheimer,
This is something I addressed back in 3.1.0 due to it causing issues with several other plugins (e.g. #98 and #103). It was something I wanted to make work since I though it looked good when scrolling content but it proved to be more effort than it was worth so now it's back to the default behaviour.
