### ISSUE TITLE
Editing the colors for Header and Editor Text not working 

### ISSUE THREAD

**Issue by o-hri** [damiankorcz/Prism-Theme#122]
**Describe the bug**
I edited the colors for both headers and editor text, and it seems to only change the color for the Inline Title Text and nothing else. 

**To Reproduce**
For instance, I tried editing the bold text color like so:
Editor>Editor Text Color> Light Theme> Bold Text Color Preset to Orange
but the colors won't update. This also applies to editing colors for italics and some headers. 

**Expected behavior**
I would expect the colors to change in real time after editing them. 

**Screenshots**
Here are screenshots of the bolded text not appearing orange. 
![image](https://user-images.githubusercontent.com/124080120/215840946-8ee39d9b-61e3-4c29-86de-1df8c494bf91.png)
![image](https://user-images.githubusercontent.com/124080120/215841034-a95e581c-e7a1-4f64-ac46-ab46825c6122.png)

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 11
 - Prism version: Prism 3.2.0
 - Color Schemes Used: Pistachio
 - Obsidian Version: v1.1.9
 - Obsidian Installer Version: v1.1.9

**Comment by damiankorcz** [comment]
Hi @o-hri,
I just tested all Header and Text Emphasis colours within the Pistachio Colour Scheme and it all seems fine on my end. Could you test this with all your plugins disabled (apart from Style Settings) and with all your CSS snippets disabled? My guess is that one of the two is interfering with the styling.

**Comment by o-hri** [comment]
Hello @damiankorcz 

I've reinstalled both Prism and Style Settings and it seems to be working fine now! 
I guess there were some issues when I initially installed it.

Thank you for your help!
