### ISSUE TITLE
[Bug] Position of Callout icons are off

### ISSUE THREAD

**Issue by dustiiiaaa** [damiankorcz/Prism-Theme#124]
**Describe the bug**
The position of title icons in callouts are positions slightly upwards.

**To Reproduce**
Insert a callout in a file with Prism theme
![image](https://user-images.githubusercontent.com/121802614/221108972-782cd4dd-c75c-4d97-8e49-6f910f0f589c.png)

**Expected behavior**
Icon should be aligned with the callout title properly. (image taken from official screenshot)
![image](https://user-images.githubusercontent.com/121802614/221108515-034866d5-89a6-42b0-a208-670cdddd549f.png)

**Setup Information**
 - Device Type: PC, but it happens on mobile too
 - Operating System: Arch Linux, Android
 - Prism version: 3.2.0
 - Color Schemes Used: Swan
 - Obsidian Version: 1.1.15
 - Obsidian Installer Version: 1.1.15
 - tested on a fresh vault with only Prism theme and Style Settings installed.

**Comment by trollsdottir** [comment]
Same for Windows

**Comment by damiankorcz** [comment]
Hi @dustiiiaaa, @Juul1 and @trollsdottir,
This is now addressed in Prism 3.2.1.
