### ISSUE TITLE
[Documentation] Clarity on location of the custom CSS to be supplied

### ISSUE THREAD

**Issue by baalajimaestro** [damiankorcz/Prism-Theme#125]
**What is your request / issue?**
I noticed that Prism supports modifying the appearance with a custom supplied CSS. (https://github.com/damiankorcz/Prism-Theme/wiki/Creating-a-Custom-Colour-Scheme-CSS-Snippet)

**Describe the solution you'd like**
I want the docs to mention more clearly on where to place this CSS.

**Comment by damiankorcz** [comment]
Hi @baalajimaestro,
To create a CSS snippet you can follow the official Obsidian help page regarding it:
https://help.obsidian.md/Extending+Obsidian/CSS+snippets
I've added this link to my guide.

**Comment by baalajimaestro** [comment]
Thanks for a very quick resolution!
