### ISSUE TITLE
[Bug] Caret symbols in callouts live preview going out of border

### ISSUE THREAD

**Issue by ashahir05** [damiankorcz/Prism-Theme#126]
**Describe the bug**
The caret symbols in callouts are going outside of the border. 

**To Reproduce**
[Steps to reproduce the behavior:
1. Use live preview with the following content:
```md
> [!error] Test
> Top level
> > [!note]
> > Nested
```

**Expected behavior**
The carets should be not be going outside the border. Rather they should behave as in the default theme.

**Screenshots**
Prism theme:
![image](https://user-images.githubusercontent.com/44367115/227715980-a6fe4d28-57b7-4370-9a8b-0c21b6db1731.png)

Default theme:
![image](https://user-images.githubusercontent.com/44367115/227716020-0c3fe77c-2acd-42aa-8220-d66da51d0bcf.png)

**Setup Information**
 - Device Type: PC
 - Operating System: NixOS
 - Prism version: 3.2.1
 - Color Schemes Used: Raven
 - Obsidian Version: 1.1.16
 - Obsidian Installer Version: 1.1.16
 - Related Community plugins: None

**Comment by ScottCTD** [comment]
+1

#127

**Comment by damiankorcz** [comment]
Hi @ashahir05 & @ScottCTD,
This should now be addressed in Prism 3.2.2. The update is available for Obsidian 1.2.0+ (Currently in Insider builds).
