### ISSUE TITLE
Quiet Outline Compatibility

### ISSUE THREAD

**Issue by dianedef** [damiankorcz/Prism-Theme#128]
**Describe the bug**
This theme is beautiful, but it doesn't show the outline made by the plugin Quiet Outline like the other theme, the line height is too small that makes it unusable. I'm no sure if the incompatibility comes from the theme or the plugin

**To Reproduce**
1. Add Quiet Outline plugin https://github.com/guopenghui/obsidian-quiet-outline
2. Add it in the right panel
3. Enable Prism theme
4. See line height too small
5
**Screenshots**
With Obsidiante theme:
![image](https://user-images.githubusercontent.com/35034946/231247799-4b94108c-9b20-40f0-9c4e-9c4fc25782c2.png)
With Prism:
![image](https://user-images.githubusercontent.com/35034946/231247899-aa02273e-e697-4326-9725-080ce5efe817.png)

**Setup Information**
 - Operating System: Windows 11
 - Prism version: Last, I installed it today
 - Color Schemes Used: Dark and Light
 - Obsidian Version: v1.1.16
 - Obsidian Installer Version: v1.1.9
 - Related Community plugins: I have a lot enabled, I don't know, will test in a clean version of Obsidian

**Comment by dianedef** [comment]
I tested it on a clean Obsidian and I don't have the bug. The problem comes from my settings or plugins then! Thanks

**Comment by damiankorcz** [comment]
Hi @dianedef,
Some of the text overlap is an issue in Prism. I'll try to address it in the next update. Thanks for reporting!

**Comment by damiankorcz** [comment]
Hi @dianedef,
This issue should now be addressed in Prism 3.2.3. Note that this update (as with 3.2.2) are currently only available for Obsidian 1.2.0+ which is at the moment an Insider build.
