### ISSUE TITLE
Folder Yellow (Vault) Icon

### ISSUE THREAD

**Issue by j4r0-code** [damiankorcz/Prism-Theme#129]
This is an awesome theme, love it.  Noob, question.  Is it possible to chang that ugly yellow (vault) folder icon to match more the dark style theme?

![image](https://user-images.githubusercontent.com/3854495/233727392-4b142f83-586b-4905-9a0b-9ed69e36fcb1.png)

**Comment by damiankorcz** [comment]
Hi @j4r0-code,
There is a guide on how to customise the Vault Banner Icon here in the Wiki: https://github.com/damiankorcz/Prism-Theme/wiki/Vault-Banner-Icon-Customisation
