### ISSUE TITLE
The Pinned icon for pinned command pallete/slash commands overlaps the command text

### ISSUE THREAD

**Issue by damiankorcz** [damiankorcz/Prism-Theme#13]
Originally reported by "Mara" on Discord.
![image](https://user-images.githubusercontent.com/7290097/140950529-86027409-26da-405b-99a1-90645c54aed2.png)

![image](https://user-images.githubusercontent.com/7290097/140950619-f6638c63-b074-405b-8aef-67d36476a4ab.png)

**Comment by psychsatani** [comment]
I have the same issue. It is also present in other areas such as in this screenshot

<img width="799" alt="image" src="https://user-images.githubusercontent.com/78266798/141359511-c84b7168-58b4-42f9-8b8c-fc393f7d50e6.png">

**Comment by damiankorcz** [comment]
Addressed in Version 1.1.0
