### ISSUE TITLE
Tablet file menu too wide

### ISSUE THREAD

**Issue by Jack-Chronicle** [damiankorcz/Prism-Theme#130]
**Describe the bug**
When you open the file menu on a Tablet, it fills the entire width of the display

**To Reproduce**
1. Go to the file menu (top right menu)
2. Open Menu
3. It opens filling the entire display

**Expected behavior**
It should only be as wide as necessary, the longest line of text maybe, possibly narrower making it multiple lines if too wide

**Screenshots**
![20230516_132527.jpg](https://github.com/damiankorcz/Prism-Theme/assets/18507378/e795e3db-2c1d-4a17-af14-c94d07146bf8)

**Setup Information**
 - Device Type: Tablet
 - Operating System: Android 
 - Prism version: 3.2.6
 - Color Schemes Used: Raven
 - Obsidian Version: 1.4.5(101)
 - Obsidian Installer Version: API(?) V1.4.1

**Comment by damiankorcz** [comment]
Hi @Jack-Chronicle,
This should now be addressed in Prism 3.3.0.
