### ISSUE TITLE
incompatible with the Markdown Formatting Assistant plugin

### ISSUE THREAD

**Issue by wei-seven** [damiankorcz/Prism-Theme#135]
**Describe the bug**
The plugin is incompatible with the Markdown Formatting Assistant plugin.
![image](https://github.com/damiankorcz/Prism-Theme/assets/63662290/ccb9a3bf-fe59-43d1-bf99-43a6e9a0e7df)

**Expected behavior**
Adapt the Markdown Formatting Assistant plugin to make it display properly.
![image](https://github.com/damiankorcz/Prism-Theme/assets/63662290/e5e56d8d-c61d-4942-964c-66ebc3c84eb2)

**Comment by damiankorcz** [comment]
The plugin is abandoned and I don't intend to support it.
