### ISSUE TITLE
Dark and unreadable file explorer in light mode

### ISSUE THREAD

**Issue by sirlaughalot90** [damiankorcz/Prism-Theme#139]
**Describe the bug**

See image. The file explorer is dark in light mode which renders the files unreadable and therefore the plugin unusable.

**To Reproduce**
I downloaded the theme and installed it, then switched from dark to light mode.

**Screenshots**
![CleanShot 2023-08-17 at 10 21 08@2x](https://github.com/damiankorcz/Prism-Theme/assets/20352339/350855dc-267f-48c0-af26-356860a4aeeb)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS Ventura 13.5
 - Prism version: 3.4.0
 - Color Schemes Used: Swan
 - Obsidian Version: 1.4.3
 - Obsidian Installer Version: 1.3.7

**Comment by damiankorcz** [comment]
Hi @sirlaughalot90, 
Could you make sure you don't have any CSS snippets or Plugins that could be causing that? I'm unable to replicate this issue on my end.

**Comment by sirlaughalot90** [comment]
Found the issue: Turning off the Minimal Theme Settings plug-in solves it.

**Comment by damiankorcz** [comment]
Hi @sirlaughalot90,
Yeah I'm pretty sure that plugin is specifically just for the Minimal theme. Glad you got it sorted!
