### ISSUE TITLE
overlapping vault name

### ISSUE THREAD

**Issue by zynth17** [damiankorcz/Prism-Theme#14]
![image](https://user-images.githubusercontent.com/45350572/144747215-524a6b83-3787-4579-8d45-9f2945df6ba6.png)

the vault name is bugging. im using windows 11

**Comment by damiankorcz** [comment]
Hi @zynth17, 

Judging by how the rest of the theme looks around the title, you appear to be missing the Style Settings community plugin which is required for the theme. There are installation instructions in this repository's readme under the Getting Started section.

Let me know if that solves your issue.
