### ISSUE TITLE
Line Spacing Is Double-Expanded When Editing Inside A Callout

### ISSUE THREAD

**Issue by nickmilo** [damiankorcz/Prism-Theme#140]
**Line Spacing Is Double-Expanded When Editing Inside A Callout**

**To Reproduce**
Create a new callout start typing and entering new lines as need.

**Expected behavior**
When entering a new line, the spacing remains normal.
Instead, the spacing is doubled.

**Screenshots**

- Prism's spacing is doubled: ![Prism](https://github.com/damiankorcz/Prism-Theme/assets/35411533/ef79dd02-6b40-4925-b78a-6043956f1473)
- Here is Default: ![Default](https://github.com/damiankorcz/Prism-Theme/assets/35411533/a8341609-f614-4784-993b-5ffafe469280)
- Here is Cybertron; ![Cybertron](https://github.com/damiankorcz/Prism-Theme/assets/35411533/6553464d-7dfb-4440-b987-d3f81051a14f)
- Here is Minimal: ![Minimal](https://github.com/damiankorcz/Prism-Theme/assets/35411533/b40ba599-7ba9-49fb-acd1-033ed87e10c2)
- Here is LYT Mode: ![LYT Mode](https://github.com/damiankorcz/Prism-Theme/assets/35411533/5c415a4b-a1c4-42e7-8c82-567c6300bb3c)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS Ventura
 - Prism version: 3.4.0
 - Color Schemes Used: Swan
 - Obsidian Version: 1.4.3
 - Obsidian Installer Version: 1.3.5

**Comment by damiankorcz** [comment]
Hi @nickmilo,
This should now be addressed in Prism 3.4.1.

**Comment by nickmilo** [comment]
Looking wonderful, (thanks for the fast fix)!
