### ISSUE TITLE
Option to Disable Editor Width Control or Alternatively Show Control Slider in Status Bar

### ISSUE THREAD

**Issue by jeetsukumaran** [damiankorcz/Prism-Theme#141]
[Please fill out the following sections as best you can to help describe the feature. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the request.]

**Is your feature request related to a problem? Please describe.**

This (GREAT!!) theme offers a way to customize the editor width through the style settings. Unfortunately, this seems to block the functionality of  [Editor with Slider](https://github.com/MugishoMp/obsidian-editor-width-slider), which I use to conveniently set the width on the flow in the editor. 

**Describe the solution you'd like**

Setting the editor width dynamically and easily from the editor screen is really nice. Would it be possible to achieve on of the following:

(a) an option to disable Prism's control of the editor width so other plugins can retain management of this
(b) Prism itself to support adjusting the editor width without need to drill through settings through, for e.g.:
     - a slider on the status bar
     - expose width adjustment to commands that we can set through hot-keys

**Comment by damiankorcz** [comment]
Hi @jeetsukumaran,
I've downloaded the plugin and it appears to work as intender for me so possibly the plugin dev has resolved this issue? I'll close this one and if it persists let me know.
