### ISSUE TITLE
Syntax Highlighting for code blocks not working in view mode

### ISSUE THREAD

**Issue by devpixde** [damiankorcz/Prism-Theme#146]
**Describe the bug**
Syntax highlighting works for several languages only in edit mode but not in view mode. (in View mode all is black)
Working languages: e.g. javascript, css, Not working languages: e.g. ruby, shell

**To Reproduce**
create a code block for ruby
in edit mode ruby code is highlighted, in view mode all text is only black.

**Expected behavior**
Syntax highlighting should work in view mode for every supported language

**Comment by damiankorcz** [comment]
Hi @devpixde,
Let me know if it happens again and if you have a reproducable way to have it happen. I'll close this until then.
