### ISSUE TITLE
Undo bold text in headings?

### ISSUE THREAD

**Issue by jeagar52** [damiankorcz/Prism-Theme#147]
I'm new to Obsidian and your excellent theme. However, I can't figure out how to unbold the text in selected headings.

I have the Style Settings plugin enabled, but can't seem to find an option to unbold headings.

I'm probably looking in the wrong places??

**Comment by damiankorcz** [comment]
Hi @jeagar52,
I don't have an option to change the font weight for Headings in Style Settings but you could revert it back to what the default theme uses with this CSS snippet:

```css
body {
    --h1-weight: 700;
    --h2-weight: 600;
    --h3-weight: 600;
    --h4-weight: 600;
    --h5-weight: 600;
    --h6-weight: 600;
}
```

You can change those vaules to your preference. If you never used CSS snippets here is how they work: https://help.obsidian.md/Extending+Obsidian/CSS+snippets

For reference: 
100 – Thin
200 – Extra Light (Ultra Light)
300 – Light
400 – Normal
500 – Medium
600 – Semi Bold (Demi Bold)
700 – Bold
800 – Extra Bold (Ultra Bold)
900 – Black (Heavy)

**Comment by jeagar52** [comment]
Thank you for your response. I tried putting a css snippet in the snippet folder and reloaded, but it didn’t seem to make any difference.

Instead, I just adjusted the heading font sizes down.

Jim

**Comment by damiankorcz** [comment]
Hi @jeagar52,
Just to be sure the file you saved in the snippet folder was `.css` and you enabled the snippet in the Apperance tab in Obsidian Settings after you reloaded?

**Comment by jeagar52** [comment]
Yes, I did all those steps. But, I know next to nothing about CSS and using it in Obsidian, so I probably screwed it up somehow.

I copied the sample you gave me into text editor, and saved it as a .css file. Then put it in the snippet folder, reloaded, and enabled.

**Comment by damiankorcz** [comment]
It appears to work on my end. Possibly another Plugin that might be impacting it or another CSS snippet?

**Comment by jeagar52** [comment]
I appreciate your help, but my workaround is fine. 🙂

Thanks for a great theme, with tons of options to customize.
