### ISSUE TITLE
Graph Lines Opacity not working

### ISSUE THREAD

**Issue by MA-121** [damiankorcz/Prism-Theme#148]
**Describe the bug**
The slider for "Graph Lines Opacity" has no noticeable effect. This is an issue especially for light mode since you can often have multiple lines crossing over the black text titles of graph notes, and it's hard to find line colors that won't obscure the black text. The opacity slider could potentially help this issue (maybe?), so I hope to try it out!

**To Reproduce**
1. Set Prism to "Light Theme/Swan"
2. Navigate to "Style Settings" plugin -> Prism Theme -> Appearance -> Graph Color Customisation -> Light Theme -> Graph Lines Color
3. Adjust the "Graph Lines Opacity" slider
4. Check Graph View to see if the lines are accordingly more opaque/transparent

**Expected behavior**
I expect the Graph Lines to become more transparent with lower values of "Graph Lines Opacity", however, I can't see any change.

**Screenshots**
Top screenshot: Graph Lines Opacity = 1 (default)
<img width="275" alt="Screenshot 2023-12-06 at 11 19 57 PM" src="https://github.com/damiankorcz/Prism-Theme/assets/82619533/c075c126-6195-4624-952f-10b3f5e7c590">

Bottom screenshot: Graph Lines Opacity = 0.10
<img width="246" alt="Screenshot 2023-12-06 at 11 21 43 PM" src="https://github.com/damiankorcz/Prism-Theme/assets/82619533/c6e6c479-c6c9-4617-a56b-3ac1c3103c6a">

**Setup Information**
 - Device Type: Macbook Pro
 - Operating System: MacOS Sonoma 14.1.1
 - Prism version: 3.4.3
 - Color Schemes Used: Swan
 - Obsidian Version: 1.4.16
 - Obsidian Installer Version: 1.4.14
 - Related Community plugins: N/A

**Additional context**
 - Thank you for the amazing plugin! Easily my favorite.

**Comment by damiankorcz** [comment]
Hi @MA-121,
This should now be addressed in Prism 3.4.4.

**Comment by MA-121** [comment]
> Hi @MA-121, This should now be addressed in Prism 3.4.4.

Works great and looks great! Thank you!
