### ISSUE TITLE
Settings too small

### ISSUE THREAD

**Issue by imeed166** [damiankorcz/Prism-Theme#15]
Can you make it bigger or make an option in the style settings plugin to change the size ?

![image](https://user-images.githubusercontent.com/38974541/145114190-bb7f68e3-2812-4b7e-88d0-f3fa2c30b46f.png)

**Comment by damiankorcz** [comment]
@imeed166 I've made some adjustments to the Settings modals and they should scale better when the Obsidian window is smaller. Released under version 1.1.2 .

**Comment by imeed166** [comment]
Yes, thank you again.
