### ISSUE TITLE
Modifying header color with the Style Settings plugins does not work.

### ISSUE THREAD

**Issue by Xiarno** [damiankorcz/Prism-Theme#150]
[Please fill out the following sections as best you can to help diagnose the issue. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the bug.]

**Describe the bug**
Using the Style Settings plugins, changing the Header Text Color does not give any effect, whether using the presets or the custom colors.

**To Reproduce**
1. Go to 'Go to 'Style Settings' 'Editor' 'Headers' 'Light Theme/Dark Theme'
2. Click on 'Click on 'Header 1 (H1) Text Color Preset ' and select any colors'
3. Exit out of the settings menu.

**Expected behavior**
The headers colors are the colors chosen in the settings.

**Screenshots**
![12379_Obsidian_KgZW8tEPLI](https://github.com/damiankorcz/Prism-Theme/assets/24660485/73b53e95-b951-4d26-afbc-c56a40f18624)
![12380_Obsidian_xSRCBg7kTK](https://github.com/damiankorcz/Prism-Theme/assets/24660485/a72c51bf-c558-4d3b-8ba5-a4b4118dcdc1)

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 10
 - Prism version: 3.4.3
 - Color Schemes Used: Indigo
 - Obsidian Version: v1.4.16
 - Obsidian Installer Version: v1.4.16
 - Related Community plugins: Style Settings

**Comment by Xiarno** [comment]
Also I just noticed that the _italic_ and **bold** text markdown also do not have their colors anymore.

**Comment by Xiarno** [comment]
**IMPORTANT:**
Disabling & re-enabling the Style Settings plugins make the colors work again. However, restarting Obsidian breaks the color again.

**Comment by damiankorcz** [comment]
Hi @Xiarno,
I can't replicate this issue. Can you try the following and see if the issue persists:
- Update your Obsidian to the latest version by redownloading and running the installer: 
https://obsidian.md/download
- Update the theme to the latest version Prism 3.4.4.
(In Obsidian go to Settings -> Appearance tab -> Click `Check for updates`)
- Update all plugins; most importantly Style Settings.
(In Obsidian go to Settings -> Community plugins tab -> Click `Check for updates`)

If this still doesn't fix the issue, can you check if this issue appears with a brand new vault just so we can eliminate any other factors causing this?
