### ISSUE TITLE
Two Tone Color Scheme

### ISSUE THREAD

**Issue by ShahriarKh** [damiankorcz/Prism-Theme#152]
Currently, we have:
✅ Minimal
✅ Border
✅ Two Tone & Border

Another one can be added:
✳ Two Tone

P.S. I tried looking at the source code to see if I can create it myself, but couldn't find out how color schemes are handled.

**Comment by damiankorcz** [comment]
Hi @ShahriarKh,
I've considered adding it as a scheme when I added this option but in my opinion it looks quite bad. Looks unfinished in a way. Hence why it is missing. I don't intend on adding it. Also the current implementation of the other options is very minimal and elegant. I don't think this would be worth adding more lines of code just to make it better.

https://github.com/damiankorcz/Prism-Theme/blob/39ed0d79438acdbfbb8c1b6511ddeb5e6066c186/src/scss/Variables/coreVariables.scss#L492-L501

![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/3af10219-a647-453d-acd0-15d45808685b)

![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/075c3695-ac2c-4512-9578-faf787e72775)

**Comment by ShahriarKh** [comment]
I see. I thought it will look good, but your screenshots clearly show that some parts require borders to look good. Thank you for your explanation 🫱🏼‍🫲🏽
