### ISSUE TITLE
Minimal Card view

### ISSUE THREAD

**Issue by Juul1** [damiankorcz/Prism-Theme#153]
**Describe the bug**
A year ago I've added the card view from the minimal theme as a css snippet. This was working great before but since the last update of prism it isn't working anymore. 

**To Reproduce**

1. Dataview of books, movies etc. 
2. css class: "cards"

**Expected behavior**
it should show a card view of the book covers/movie covers etc. but the cards are really small like 5%. 

**Screenshots**

Minimal:
![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/da5909bc-6be5-4662-92c8-90b36cc38445)

Prism:
![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/69329f2f-9a59-47a3-8e3b-65f91c479dc4)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS Sonoma
 - Prism version: 3.4.3
 - Color Schemes Used: Light
 - Obsidian Version: 1.5.3
 - Obsidian Installer Version: 1.4.13
 - Related Community plugins: In minimal it is working...

**Additional context**
[Add any other context about the problem here]

**Comment by Juul1** [comment]
@damiankorcz I've tried different themes as well. But they have the same issue of the small cards, so it's only working with the minimal theme.

**Comment by damiankorcz** [comment]
Hi @Juul1,
Considering you said that you've gotten the Minimal Cards snippet a year ago, could you try grabbing the following part of the Minimal theme into a new snippet to replace your current Cards snippet and see if that resolves the issue?
https://github.com/kepano/obsidian-minimal/blob/master/src/css/main.css#L1947-L2254

**Comment by Juul1** [comment]
Hi @damiankorcz, Thanks. I've found the adjusted snippet last week, but forgot to share it here. 
See youtube channel for PRAKASH JOSHI PAX. Link to [snippet](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbHVxT3hsc0Z0NFRnUVlPcTk1SlFhbUIxVFB3d3xBQ3Jtc0trdWV3Q2xOQWFjNnBrNFRiZDRBbTJ6Z2R1c0E5ZGlsN1lzdlY5SWxGSlB0ZGJQd1p0bFNFMDl6ekRuUkJNLWVMZEIwSzVtUk8tbHFmS2ZvV2xMRmVZS0p4Ym5MYmNfb0ZOV1hoTDZhdFJ1bTRiUGl3VQ&q=https%3A%2F%2Fwww.patreon.com%2Fposts%2Fminimal-theme-96273589&v=zeDYRQBMc10)
