### ISSUE TITLE
Issues with 'backlinks in document' on iOS

### ISSUE THREAD

**Issue by kxngrocafella** [damiankorcz/Prism-Theme#155]
**Describe the bug**
The backlinks inside of a note and displayed at the bottom do not behave well on iOS. When results are expanded, the screen will not scroll to the bottom (cutting off the backlink results). To see the bottom, you need to force a scroll, which when you let you reverts to normal and cuts off the backlinks again.

**To Reproduce**
1. Go to any note with backlinks.
2. Click 'collapse results' button (expanded view)

**Expected behavior**
The bottom of the scroll of the page should be after the backlinks feature. Normal page scroll behaviour.

**Screenshots**
![IMG_0838](https://github.com/damiankorcz/Prism-Theme/assets/20718287/3dd643e5-e282-481b-8a45-1e6fedf4004f)
Screenshot demonstrates the screen scrolled all the way to the bottom, but the 'unlinked mentions' is cut off

**Setup Information**
 - Device Type: iPhone 15
 - Operating System: iOS
 - Prism version: 3.4.3 - btw this is screwed up on iOS as well (it is cut off and above the screen).
 - Color Schemes Used: Standard. Auto Light Dark.
 - Obsidian Version: Latest.
 - Obsidian Installer Version: 
 - Related Community plugins: 
 - Plugins -> Installed plugins (Ones that are enabled when the bug occurs)]

**Additional context**
[Add any other context about the problem here]

**Comment by damiankorcz** [comment]
Hi @kxngrocafella,
I'm looking into this issue although on Android and can replicate it. However I can also see it happen with the default theme. I have found a potential solution but will first relay it back to Obsidian devs to see if it can get fixed upstream. I'll keep this issue open for now until I know how to handle it.

**Comment by damiankorcz** [comment]
Hi @kxngrocafell,
Just coming back around to this issue and as far as I can tell it no longer happens. Let me know if you still have it. I'll close the issue for the time being.
