### ISSUE TITLE
Folder colors in prism color style

### ISSUE THREAD

**Issue by Juul1** [damiankorcz/Prism-Theme#156]
[Please fill out the following sections as best you can to help describe the feature. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the request.]

**Is your feature request related to a problem? Please describe.**
No. I'm using the snippet [Iterative Rainbow Folder Backgrounds.css](https://forum.obsidian.md/uploads/short-url/ygofZrBpeLfGVyUAQRtrMBHfXyp.css)  from https://forum.obsidian.md/t/iterative-rainbow-folder-colors-css/21066
but the colors are not taken over from the css snippet. And if I replace them with for example the white hex colour it doesn't change anything and the colors are not really the prism theme colors or am I wrong? 

See: 

![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/c70bfd55-cd82-49f7-8b58-81258ba672de)

**Describe the solution you'd like**
I would like to see the prism theme colors. 
In Dark mode it looks good: 

![image](https://github.com/damiankorcz/Prism-Theme/assets/7290097/908336d7-f225-4570-b6b6-e42ddc2b7b71)

**Describe alternatives you've considered**
None....

**Additional context**
None....

**Comment by damiankorcz** [comment]
Hi @Juul1,
I've added a native implementation of Coloured Folders in Prism 3.5.0.
You can find it in: Style Settings -> Prism Theme -> User Interface -> Sidebar and Main Workspace -> File Explorer -> Colored Folders
