### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by damiankorcz** [damiankorcz/Prism-Theme#16]
This Issue will be used to track commits made to improve the Mobile Support. If you have any special requests for the Mobile theme let me know below.

**Comment by se-cung-syu-ngai** [comment]
I've noticed that in the file tree view, the new folder and new note buttons are covered by the cute vault graphic. Also the edge of the side bar is cut off. I'm loving this theme otherwise.

**Comment by damiankorcz** [comment]
@se-cung-syu-ngai, Thanks! Yeah the mobile side of the theme hasn't really been touch yet so it is quite broken in the current state. Will hopefully get around to it soon™ 😅

**Comment by damiankorcz** [comment]
Officially supported starting with v2.1.0. If you encounter any problems create new issues as usual!
