### ISSUE TITLE
Custom color scheme colors optioni breaking the theme

### ISSUE THREAD

**Issue by Groomingstream9** [damiankorcz/Prism-Theme#161]
**Describe the bug**
Prism theme doesn't work and breaks when chosen custom color in color scheme parameter (i.e. raven)

1. Go to Settings > Community plugins > Style settings > Prism Theme> Appearance > Accent, Color Schemes and Style > Dark theme > Color scheme
2. Configure any colors in 'Custom Color Accent Tuning' Down below
3. Choose "Custom" in Color Scheme parameter

**Expected behavior**
Colors should change to chosen custom ones

**Screenshots**
![image](https://github.com/damiankorcz/Prism-Theme/assets/22529393/ea77ea5f-9eb7-41ea-bd69-eb0f2fc3f76f)

**Setup Information**
 - Device Type: PC
 - Operating System:Windows 10
 - Prism version: 3.4.4
 - Color Schemes Used: Raven -> Custom
 - Obsidian Version: 1.5.15
 - Obsidian Installer Version: 1.4.13 
 - Related Community plugins: Obsidian Style Settings

**Comment by damiankorcz** [comment]
Hi @Groomingstream9,
I think you misunderstood things a little mixing 2 separate features.

The `Custom Color Accent Tuning` option is to set a custom Accent Color. You select the colors you want there and then set the `Accent Color Preset` to `Custom` to use it.

The `Custom` option in `Color Scheme` is intended for fully custom color schemes which the process of creating is described in the following wiki guide: https://github.com/damiankorcz/Prism-Theme/wiki/Creating-a-Custom-Colour-Scheme-CSS-Snippet

As for Obsidian looking broken after setting the `Custom` option in `Color Scheme`, I have already been made aware of this in issue #158 and have addressed it ready for the next Prism release.

Sorry for the inconvenience.
