### ISSUE TITLE
Template Hotkey for Templater

### ISSUE THREAD

**Issue by eboof** [damiankorcz/Prism-Theme#163]
[Please fill out the following sections as best you can to help describe the feature. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the request.]

**Is your feature request related to a problem? Please describe.**
[It may be me but in Template Hotkeys I'm unable to create a Hotkey. THere is the option to Add but clicking the + takes you to the filter and no further ]

**Describe the solution you'd like**
[In the demo by Sergio I was following, there is a hotkey icon in lieu of the + key.]

**Describe alternatives you've considered**
[I can create an intermediate folder for my files using the default template but that negates the freedom to create a random note in any folder and use the hotkey to assign the template]

**Additional context**
[As I said it may be me and finger trouble but your help would be appreciated]

**Comment by damiankorcz** [comment]
Hi @damiankorcz,
This doesn't seem to be a theme specific issue. Don't really think a theme could change a behaviour like that. I've tried it with the default theme and it appears to do the same. I'd submit this issue with the Templater dev.

Also, if you mean this video then it appears to be almost 2 years old so there is a good chance something change with Templater since.

**Comment by eboof** [comment]
Thanks Damian for your very quick response.I have a lot to learn and I’m not exactly young. You know old dogs new tricks.Thanks again and cheers,Rob Lovett0418 718 ***@***.*** 26 Mar 2024, at 11:09 AM, Damian Korcz ***@***.***> wrote:﻿
Hi @damiankorcz,
This doesn't seem to be a theme specific issue. Don't really think a theme could change a behaviour like that. I've tried it with the default theme and it appears to do the same. I'd submit this issue with the Templater dev.
Also, if you mean this video then it appears to be almost 2 years old so there is a good chance something change with Templater since.
https://www.youtube.com/watch?v=QpJbeP8f55A
