### ISSUE TITLE
In Obsidian 1.6.0 on macOS, the "stoplight" overlaps with the top of the left sidebar

### ISSUE THREAD

**Issue by JoelAnderson-UU** [damiankorcz/Prism-Theme#164]
Love the plugin!  But the prolbem is what the title says.  Here's the screenshot.  This is not affecting the default theme or other third-party themes.

As far as I can see, I don't have anything turned on in Style Settings that affects this.

<img width="137" alt="Screenshot 2024-05-12 at 22 15 53" src="https://github.com/damiankorcz/Prism-Theme/assets/102857667/4894ce12-8d3b-4cd3-8bff-26c3c0f57fb3">

**Comment by damiankorcz** [comment]
Hi @JoelAnderson-UU,
Just to confirm this is happening with Prism 3.5.1? I don't have a Mac machine to test with but will see if I can figure out what might be causing it since you said it's not happening with default theme.

**Comment by JoelAnderson-UU** [comment]
Thanks!  Yes, this is on Prism 3.51.  I'm guessing it's related to the layout changes introduced with Obsidian 1.16, which moves things around in the left sidebar.

**Comment by JoelAnderson-UU** [comment]
Yes!  That takes care of it.  Thanks so much.

**Comment by damiankorcz** [comment]
Hi @JoelAnderson-UU,
This issue should now be resolved in Prism 3.5.2. You can now switch back to the usual theme file.
