### ISSUE TITLE
iOS safe zones with sidebar are a little funky

### ISSUE THREAD

**Issue by lachholden** [damiankorcz/Prism-Theme#168]
**Describe the bug**
On my iPhone 14 Pro,  the sidebars look a little strange with the way the interacts with the rounded corners of screen plus the dynamic island.

**To Reproduce**
Open the sidebar

**Expected behavior**
The sidebar is fully visible and looks natural
- the corners of the sidebar don't go "off screen" in the rounded corners of the phone
- the top of the sidebar doesn't intersect strangely with the dynamic island/clock/wifi/etc

**Screenshots**
(forgive the cracked screen protector and the average photo quality, but the screenshot obviously doesn't really capture how it looks on the hardware)
![Photo on 22-5-2024 at 8 11 am](https://github.com/damiankorcz/Prism-Theme/assets/4650587/5d8a887d-0d79-4a51-af31-d8aa84da58eb)

**Setup Information**
- iPhone 14 pro
- Prism 3.5.0
- Obsidian 1.5.12 (134)
- iOS 17.4.1

Thanks! 😁

**Comment by damiankorcz** [comment]
Hi @lachholden,
I've implemented a fix which appears to have improved this, as far as I can test on Android (don't have any Apple devices). Should be resolved with Prism 3.5.3
