### ISSUE TITLE
Add support for the Note toolbar plugin

### ISSUE THREAD

**Issue by FeralFlora** [damiankorcz/Prism-Theme#169]
**Is your feature request related to a problem? Please describe.**
I was looking to try out the [Note toolbar plugin](https://github.com/chrisgurney/obsidian-note-toolbar), but got stuck trying to make the toolbars look nicer, because it was looking really strange (see image). Then, after switching to the default theme, I realized that it was a theme issue.

Here's what a note toolbar looks like when using Prism:

![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/080a6c9a-60ed-4303-ad91-d9705df9a244)

Here's the settings I've applied when configuring the note toolbar (refer to the plugin docs to see what each option ought to do: 
https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Styling-toolbars#how-styles-are-applied).

![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/d605493a-2ef8-4aa3-9ee9-fda66b97994e)

As you can see, the Note toolbar shouldn't have a border, according to my settings, and each item should be styled as a button.

**Describe the solution you'd like**
I would like for the note toolbar to be styled correctly while using the Prism theme. Correctly meaning that the style settings set in the Note toolbar's settings actually apply. As they do here with the default theme:

![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/2a978b12-b7f8-4bfc-8a29-502a8bf976cc)

**Describe alternatives you've considered**
Making this request in the Note toolbar repo instead. Sorry if this request is misplaced. However, as you can see below, Prism seems to be the theme that deviates the furthest from the expected styling.

**Additional context**
Note toolbar styling with some other themes:

### Polka
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/4168ef89-306c-4b2f-ae0d-20babdbadda2)

(note toolbar border is the same as the one applied to callouts)

### Aura
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/82e66d8d-20db-4b6f-9dc2-5b02f4c1e2f2)

### Minimal
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/282eac07-b803-4e19-af26-42e8c0322b0d)

### AnuPpuccin
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/7332723e-b434-4e44-acfb-735d342ccf97)

### Border
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/714a417d-4ffc-4cca-8c83-7e6cb247ce75)

### MagicUser
![image](https://github.com/damiankorcz/Prism-Theme/assets/33608083/32d7023b-aac5-41f4-96de-5ddf0d45e797)

**Comment by damiankorcz** [comment]
Hi @FeralFlora,
This should be resolved in an upcoming update. I'll close this issue and let you know when it's out. Not entirely sure why the plugin dev decided to use Callout styling CSS classes for this toolbar, it's what caused the border since my changes to callouts were applying to it. Had to specifically exclude them from this plugin.

**Comment by FeralFlora** [comment]
> This should be resolved in an upcoming update.

Nice, thank you!

> Not entirely sure why the plugin dev decided to use Callout styling CSS classes for this toolbar

Yeah, I don't know either. Perhaps it has something to do with the plugins other ability to render actual callouts as toolbars, and consistency in this regard? https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Note-Toolbar-Callouts

**Comment by damiankorcz** [comment]
Hi @FeralFlora,
This should now be addressed in Prism 3.5.3. Note that the release requires Obsidian app version 1.6.0 or above.

**Comment by chrisgurney** [comment]
@damiankorcz Thanks so much for accommodating my plugin in your theme.

Per @FeralFlora I used callout CSS for the toolbar so that the [Note Toolbar callouts](https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Note-Toolbar-Callouts) capability works. (The plugin originally started as just a CSS snippet.)
