### ISSUE TITLE
Font settings don't work as they are supposed to. 

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#17]
updating editor font setting updates the whole UI, including the menus, edit and preview modes. On other themes choosing different fonts for edit and preview modes work as expected. 

![image](https://user-images.githubusercontent.com/5840669/146804282-48f746ab-cf5e-4f90-9268-6c44b035f471.png)
![image](https://user-images.githubusercontent.com/5840669/146804450-a15abf34-da15-4ae6-88d8-341382185114.png)

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.2.0.
