### ISSUE TITLE
Bold, italic text not keeping the settings.

### ISSUE THREAD

**Issue by flisnh** [damiankorcz/Prism-Theme#170]
**Describe the bug**
Hi.

I am using style settings plugin to customize Prism Theme to my liking. If I open the app after restarting or completely closing it, the plugin does not work. It is on, but the bold text does not change its color like I told it to in its settings, or the italic text. Correction, the theme of the app changes (the border colors), but the bold texts and italic do not. In order for that to work, I have to open the settings, go to community plugins and turn the style settings off and on, kind of restarting it. Then, everything works as it should. But after i close it completely or restart my PC, the same issue occurs.

**To Reproduce**
1. Open the app.
2. There you go.

**Expected behavior**
For bold, italic text to change colors every time I restart the app.

**Screenshots**
Shouldn't be like this:
![image](https://github.com/damiankorcz/Prism-Theme/assets/79057430/2ee481ac-c4cb-4857-b540-049ca938c44c)

After turning off and then on the prism theme in community plugins:
![image](https://github.com/damiankorcz/Prism-Theme/assets/79057430/cb42694c-9805-4214-8430-01fd49a8681f)

**Setup Information**
 - Device Type: Phone, laptop
 - Operating System: Windows 11, Android.
 - Prism version: 3.4.3
 - Color Schemes Used: Light - Swan, Dark - Indigo. Currently using dark.
 - Obsidian Version: 1.5.12
 - Obsidian Installer Version: 1.5.3
 - Related Community plugins: Style settings. It's the only plugin I have.

**Additional context**
No.

**Comment by damiankorcz** [comment]
Hi @flisnh,
I think this will be resolved with the next update. It's related to the fix I did for this issue: https://github.com/damiankorcz/Prism-Theme/issues/133#issuecomment-2126148920

**Comment by damiankorcz** [comment]
Hi @flisnh,
This should now be addressed in Prism 3.5.3. Note that the release requires Obsidian app version 1.6.0 or above.
