### ISSUE TITLE
Arrow on parent folded list behaving strange

### ISSUE THREAD

**Issue by kxngrocafella** [damiankorcz/Prism-Theme#172]
**Describe the bug**
Arrow on parent folded list behaving strange. Think I noticed this issue after updating to Prism 3.5.3.

**To Reproduce**
1. Start any bulleted, numbered or checkbox list i.e. Parent A in attachment.
2. Indent in and create a few child/nested lists.
3. Come out and place cursor on Parent A - we see the foldable list arrow behave normally.
4. Fold the list, then move the cursor away from Parent A to the next list item (e.g. Parent B).
5. Foldable list arrow moves from the expected position and instead covers the text.

**Expected behavior**
Foldable list arrow doesn't move when list is folded and you move the cursor away to a new line in the list.

**Screenshots**
Gif attached.

**Setup Information**
 - Device Type: iPhone 15 Pro and MacBook Pro
 - Operating System: Mac and iOS (whatever the latest is). 
 - Prism version: 3.5.3
 - Color Schemes Used: Swan/Raven
 - Obsidian Version: 1.5.12
 - Obsidian Installer Version: [Found in Settings -> About tab]
 - Related Community plugins: I disabled all community plugins to test, only kept style settings enabled.
 - Plugins -> Installed plugins (Ones that are enabled when the bug occurs)]

**Additional context**

![CleanShot 2024-06-04 at 21 03 25](https://github.com/damiankorcz/Prism-Theme/assets/20718287/af945a2e-7911-4b05-9da0-369ab3e6a643)

**Comment by damiankorcz** [comment]
Hi @kxngrocafella,
I can't seem to replicate this issue. All seems to work fine on my end. Could you please update your Obsidian (current latest public release is 1.6.5 released today) and see if you still encounter it?
Thanks
