### ISSUE TITLE
Collapsible callout button is obstructed by code button

### ISSUE THREAD

**Issue by pinetreemoonlight** [damiankorcz/Prism-Theme#175]
### Describe the bug
With Prism Callout styling enabled and using a native collapsible callout (i.e. adding a "+" or a "-" after the square brackets of the callout command), **the buttom to collapse and expand the callout is obstructed behind the code button**, making it hard to click.

![Screenshot 2024-07-22 235739](https://github.com/user-attachments/assets/bb699c8a-51ec-48b9-94db-e5fbbe423bd0)

### To Reproduce
**1) Enable Prism callout styling:**
Style settings --> Prism Theme --> Feature toggles --> Disable Prism Callout Styling = set to disabled

**2) Add any collapsible callout like this:**
```
> [!info]+ Here's a collapsible callout block. 
> test
```

### Expected behavior
With native styling, the collapse/expand button is next to the callout header, not obstructed by the code button:

![Screenshot 2024-07-22 235927](https://github.com/user-attachments/assets/005b5247-3d3a-4bec-8488-2ea7091c6b39)
 
### Setup Information
 - Device Type: PC and Mac
 - Operating System: Windows 11 and MacOS Sonoma
 - Prism version: [Found in Settings -> 3.5.3
 - Color Schemes Used: Swan and Latte (same with any color scheme)
 - Obsidian Version: 1.6.7
 - Obsidian Installer Version: 1.6.5
 - Related Community plugins: none

**Comment by damiankorcz** [comment]
Hi @pinetreemoonlight,
The entire title is clickable and functions as the collapse and expand for the callouts. You don't have to click the icon.

**Comment by pinetreemoonlight** [comment]
> Hi @pinetreemoonlight, The entire title is clickable and functions as the collapse and expand for the callouts. You don't have to click the icon.

Okay, you are right, stupid of me. I guess then it's only a very minor aesthetic issue, if anything.
