### ISSUE TITLE
Renaming kanban list gets all weird

### ISSUE THREAD

**Issue by Fnige** [damiankorcz/Prism-Theme#179]
**Describe the bug**
When renaming a list's the text thingy becomes all thin and vertical

**To Reproduce**
1. Make a kanban board
2. Make a list with any name
3. Double click list name (or any other way to let yourself rename the list)
4. Oh that text is vertical

**Expected behavior**
The text box to stay wide and not be all thin

**Screenshots**
No editing:
![image](https://github.com/user-attachments/assets/75d48433-c7ed-48bf-99d7-59f2c46ff007)

Editing with prism
![image](https://github.com/user-attachments/assets/80f2f8a7-67d0-492e-990c-317f8594c255)

Editing with no theme
![image](https://github.com/user-attachments/assets/22617190-916d-4a5c-9f32-c7959ce6f54f)

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 11
 - Prism version: 3.5.4
 - Color Schemes Used: Indigo
 - Obsidian Version: 1.7.4
 - Obsidian Installer Version: 1.4.16
 - Related Community plugins: Kanban (2.0.51), Style Settings (1.0.9)

**Comment by damiankorcz** [comment]
Hi @Fnige,
This should now be resolved in Prism 3.6.0.
