### ISSUE TITLE
Backlinks in document is a bit broken

### ISSUE THREAD

**Issue by Mpic** [damiankorcz/Prism-Theme#18]
![image](https://user-images.githubusercontent.com/5664276/146987824-6023e7d7-908d-4b72-a002-0ce7431fcd4d.png)

The four icons (Collapse results, Show more context, Change sort order and Show search filter) are cut as they show like this when in right sidebar :
![image](https://user-images.githubusercontent.com/5664276/146987967-b594b2cc-0572-473c-b217-62ebe2f61c9d.png)

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.2.0.
