### ISSUE TITLE
Code highlight for light theme makes some elements harder to see.

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#2]
Especially string types on some languages are highlighted as light green. If there is a setting to change it, I couldn't find it. Changing the highlight pallette to something more readable or any customization that I can apply is welcomed. Btw, awesome theme :)

**Comment by damiankorcz** [comment]
Also mentioned on Discord by "Hamster151" in a DM. Contrast issue with other colours is also not idea in the white theme currently. Will be addressed in a coming update. Potentially some customisation down the line will be added as well.

Thank you for reporting back @yigitozgumus !

**Comment by damiankorcz** [comment]
Hi @yigitozgumus,
There have been quite a few things done to improve the overall readability of the Light Theme in the latest update version 1.1.0. Let me know if that's better!

**Comment by yigitozgumus** [comment]
Hello @damiankorcz,
Yes,It seems like readability really improved in the Light theme. Great work!
