### ISSUE TITLE
[Bug] Header colors don't change in dark mode

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#23]
Live preview works great. Thank you for this beautiful theme. After the theme is loaded and without any change on style settings, dark theme does not show the header font colors correctly. It works for light theme.
<img width="731" alt="Screen Shot 2022-01-02 at 09 38 52" src="https://user-images.githubusercontent.com/5840669/147868368-0165f317-e231-4369-82ce-a978bc22a019.png">
<img width="731" alt="Screen Shot 2022-01-02 at 09 38 45" src="https://user-images.githubusercontent.com/5840669/147868369-b1690014-c406-4057-b1ce-b4556eab83a7.png">

**Comment by yigitozgumus** [comment]
I might opened this issue too quickly. Header colors and background customization work. I think the default settings for the header text color is wrong though. It is set to dark. When I changed to light, everything works as expected. I am leaving this issue open if anything related to this comes up.

**Comment by damiankorcz** [comment]
Thank you for spotting it! Should now be addressed in Version 1.2.1
