### ISSUE TITLE
Create Theme Feature Snippets

### ISSUE THREAD

**Issue by Craftidore** [damiankorcz/Prism-Theme#24]
Using the `<mark class="red"></mark>` you provide an excellent feature to the theme. However, if I move a note with that HTML into another vault, it won't retain its color. This is specifically a problem for me because I use nested vaults, each with a  different theme. I avoid using colored marks because in my nested vaults they will show up as ordinary highlights.

As such, would you please make a snippet with the CSS for mark classes [like SlRvb has done with her ITS Theme](https://github.com/SlRvb/Obsidian--ITS-Theme)?

Thank you so much for your work on this theme!

**Comment by damiankorcz** [comment]
Hi @Craftidore,
I'm currently in the process of moving my theme into a SASS workflow and with that I'm hoping to organise the theme such that some components like the Mark Highlight System and others that aren't too heavily integrated into the theme to be able to become independent snippets for use with other themes while still remaining integrated in the theme. So I'd say expect this to be the case in the near future.

**Comment by Craftidore** [comment]
That's wonderful! Thank you so much.

**Comment by damiankorcz** [comment]
The Mark Highlight System will be coming in the next update (v1.3.0) 🥳. I'll have it available in Prism's Repo under `/src/snippets` as a `.css` ready for use in Obsidian and a corresponding folder with `.scss` that make up the snippet. Will come with it's own Style Settings menu that has the same features as the features inside Prism. There might be some issues with some themes that have their own Mark System so will need to adjust things on per theme basis.

Here are a few examples of it working in other themes:
### Minimal Theme
![image](https://user-images.githubusercontent.com/7290097/150849290-521f94e7-232a-407e-aca7-513325d2fa6f.png)
### Primary Theme
![image](https://user-images.githubusercontent.com/7290097/150851296-ac2954b0-4d90-4162-9a8b-2a40f041379f.png)
### ITS Theme
![image](https://user-images.githubusercontent.com/7290097/150851230-a0cddc31-e757-4621-bcfa-f7b9be40b8f5.png)

Feel free to suggest other parts of Prism you'd like to see as a snippet in another issue. *Just please don't say Headers... please don't say Headers...  🤣*

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.3.0.
