### ISSUE TITLE
Feature request: Add margin/padding as header style settings

### ISSUE THREAD

**Issue by emilyeserven** [damiankorcz/Prism-Theme#27]
I know I could do this in CSS, but I feel it's easier to work with if it's all in the same place.

**Comment by damiankorcz** [comment]
Hi @emilyeserven, I'm just looking into implementing this. Would you want this to be adjustable per-header per-theme (Light/Dark) or just as an overall setting for all headers at once?

**Comment by emilyeserven** [comment]
Personally all I feel I need is an overall setting per header, but it feels
like that might conflict with (or just feel "off" considering) how things
are currently set up, which is per header per theme.

**Comment by damiankorcz** [comment]
Hi @emilyeserven,
With the release of v2.0.0 there are settings to change the margin around the headers (Go to Style Settings -> Prism Theme -> Editor -> Header Margin Size).

Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating.

Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
