### ISSUE TITLE
Files explorer cannot display too many files with Prism-Theme

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#28]
@damiankorcz 
## Problem
finding that sometimes files can't be displayed normally with Prism-Theme. And I try to build a new vault with just one third-party plugin: **style setting**, using **Prism-Theme**.Then I start to create new note until problem reappearance.

https://user-images.githubusercontent.com/98091664/150461607-6aa4db8f-8b5f-4bf0-b297-e81b838afbde.mp4

## Environment
os: win 10
ob ver: 0.13.19
prism ver: v1.2.1

## Last
i'm a beginner of ob and **Prism** is a wonderful theme 😊😆
_hope for your reply asap_

**Comment by damiankorcz** [comment]
Yeah I can recreate the issue on my end. Not sure what is causing it yet. Will look into it!

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.3.0.
