### ISSUE TITLE
Bug: minor styling bug when using sliding pane's rotated headers

### ISSUE THREAD

**Issue by chrisgrieser** [damiankorcz/Prism-Theme#29]
<img width="160" alt="Screenshot 2022-01-23 15 20 20" src="https://user-images.githubusercontent.com/73286100/150684426-2bdf9c09-62f8-4eb7-8c2c-65d51441e476.png">

🏴‍☠️

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.3.0.
