### ISSUE TITLE
support for plugin "Emoji-Toolbar"

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#32]
@damiankorcz hello again

## Advice

emoji-toolbar showed with default theme like this:
![image](https://user-images.githubusercontent.com/98091664/151650269-6a328347-0e13-4fc1-b5c9-621e796794c3.png)

and it showed with Prism-theme like this:
![image](https://user-images.githubusercontent.com/98091664/151650355-f109a1bf-e895-409d-aa6e-bd37f106376b.png)

## Environment

os: win 10
ob ver: 0.13.19
prism ver: v1.4.0

## Last

hope for your reply asap😊

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.5.0.
