### ISSUE TITLE
sticky backlinks toolbar bug

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#33]
@damiankorcz hello again

# Bug

as you see, the backlinks toolbar shows on the top layer in the **reading** view
![image](https://user-images.githubusercontent.com/98091664/152715499-974d1c81-a04b-4105-88d3-c260f353af83.png)

# Environment

os: win 10
ob ver: 0.13.19
prism ver: v1.5.0

# Last

hope for your reply asap😊

**Comment by damiankorcz** [comment]
This should now be addressed in Version 1.5.1.
