### ISSUE TITLE
other appearance customizations are not displayed(except Prism-Theme) in Style-Setting Plugin since update

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#36]
@damiankorcz hello again
---

# Problem

one day i notice i couldn't customize **ITS-Checkboxes snippets**(#20) in **Style-Setting Plugin**. then i open another vault with an older version of **Prism-Theme** and find it works normally.
![image](https://user-images.githubusercontent.com/98091664/153416012-5f2d37e5-5b0c-47a3-a3ce-9efb785e7919.png)
_v1.3.0_
![image](https://user-images.githubusercontent.com/98091664/153416212-df00989a-baa5-4e70-90fc-661b0ebfd8e3.png)
_v1.5.2_
it seems all appearance customizations disappear except **Prism-Theme**

# Environment

os: win 10
ob ver: 0.13.19
prism ver: v1.5.1

# Last

_hope for your reply asap_ 😊

**Comment by AiurArtanis** [comment]
and i try to update the **Style-Setting Plugin** to the latest version and it still remains the bug

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, I don't seem to have this issue. I'm on Obsidian v0.13.24, Prism v1.5.2 and Style Settings v0.4.9. Since you are on an older version of Obsidian try updating to the latest public build. Should be v0.13.23. See if that helps at all. Not sure what might be causing this.

![image](https://user-images.githubusercontent.com/7290097/153454346-5cbac16e-3477-4086-9dc9-f25f535c515a.png)

**Comment by AiurArtanis** [comment]
emmm i try to update ob to ver23 then i create a new vault with only **Prism-Theme**, css snippet and **Style-Setting**, and the bug still stays:
![image](https://user-images.githubusercontent.com/98091664/153527797-21fc39bd-aa73-41e6-b615-dc532a59d676.png)

---

btw, where is this ver24 ob 🤣
the release from official page remains ver23:
![image](https://user-images.githubusercontent.com/98091664/153527414-d0926dd6-128d-47da-a30c-111288aa4c9d.png)

**Comment by damiankorcz** [comment]
It seems that we are using different snippets for the ITS Checkboxes. This is where the latest one is: https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/S%20-%20Checkboxes.css

Also version Obsidian v0.13.24 is the current insider version. I'll test more on this tomorrow.

**Comment by AiurArtanis** [comment]
> It seems that we are using different snippets for the ITS Checkboxes. This is where the latest one is: https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/S%20-%20Checkboxes.css

i think it is nothing with this CSS snippet because i find the same case in plugin **Buttons** 
![image](https://user-images.githubusercontent.com/98091664/153532575-61409961-959e-4f8e-82a8-dd7bd947f967.png)
_prism:v1.3.0_

![image](https://user-images.githubusercontent.com/98091664/153532600-341f4123-d9b4-4114-9736-4d95ad153939.png)
_prism:v1.5.2_

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, I've tried again on a new vault with a fresh copy of Prism v1.5.2, Style Settings v0.4.9, Buttons v0.4.16 and the latest version of the ITS Checkboxes snippet. The Buttons Style Settings didn't show up for me initially so I made sure to comment out elements of the theme and slowly rebuild it by re-adding each .scss back to it. Although it's showing correctly now I see no changes in git (?) Really don't understand what is going on. I've pushed the rebuilt version of the theme to the main branch so you should be able to update and see if that does anything. Note I haven't changed the theme version number so don't worry about that.

**Comment by AiurArtanis** [comment]
> I've pushed the rebuilt version of the theme to the main branch so you should be able to update and see if that does anything. Note I haven't changed the theme version number so don't worry about that.

i checked the commit history and didn't find the fix scss😂. or you try to fix it in v1.6.0 altogether?

**Comment by AiurArtanis** [comment]
it's fixed on the latest OB though i'm not sure if this update indeed works or other reason
