### ISSUE TITLE
support for plugin "TagFolder"

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#37]
@damiankorcz hello again

## Advice

support for the plugin **TagFolder** (a plugin like File Explorer that list the notes by tags)
![image](https://user-images.githubusercontent.com/98091664/153421441-ffcbcd71-bd27-4e41-b207-54ccc4bdd1a3.png)
_in Prism-Theme_
![image](https://user-images.githubusercontent.com/98091664/153421585-768bd9f9-5d7a-4916-999d-7ca144938796.png)
_in default theme_

## Environment

os: win 10
ob ver: 0.13.23
prism ver: v1.5.2

## Last

in fact, there are other niche plugins to be supported and I'm struggling if i should submit issues for these all 😂

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, I'll look into this one. If you have a number of plugins that only have small elements that need fixing feel free to submit them all in one issue. It will be easy to track that way.

**Comment by AiurArtanis** [comment]
> Hi @AiurArtanis, I'll look into this one. If you have a number of plugins that only have small elements that need fixing feel free to submit them all in one issue. It will be easy to track that way.

ok plugins that only have small elements that need fixing feel free lists below:
- **Dictionary** : to adapt the toolbar for the theme
![image](https://user-images.githubusercontent.com/98091664/153529362-a367399d-3059-4f36-81b2-3ecc223c4873.png)

- **Jumo-to-Date** : to adapt the calendar view for the theme
![image](https://user-images.githubusercontent.com/98091664/153529968-6941d4be-9385-42fb-be6f-ac6f1a18a09d.png)

- **Icons** : to change the the SVG icon to the UI Accent color(just like plugin **Icon Folder**):
![image](https://user-images.githubusercontent.com/98091664/153531941-a347b5a6-ccb4-45a0-80b6-bc232f87e8c3.png)

other plugin:
- **Slides** (core plugins) / **Advanced Slides** : i don't know which is appropriate that theme supports the plugin or the plugin suits the theme

**Comment by AiurArtanis** [comment]
- [obsidian-hover-editor](https://github.com/nothingislost/obsidian-hover-editor): quite a potential plugin but still a beta plugin temporarily. 

https://user-images.githubusercontent.com/98091664/158966819-4270fd52-9400-4503-8c35-c8565879e8ca.mp4

_popup view with Prism theme_


https://user-images.githubusercontent.com/98091664/158967678-54c22fdb-1461-434c-8ddd-d68aa3ae8e23.mp4

_popup view with default theme_

compared with 2 demos above, there are some differences:
1. scroll bar and page margin(or padding ?) makes popup view look smaller with Prism theme
2. it looks blurry when popup view shows at beginning with Prism theme
3. “Pin” button animation with default theme

**Comment by damiankorcz** [comment]
Hi @AiurArtanis,
With the release of v2.0.0 the following plugins are now styled: Tag Folder, Dictionary, Jump to Date and Hover Editor. Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating. Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
