### ISSUE TITLE
Obsidian Tabs Row cut off

### ISSUE THREAD

**Issue by MalignantCarp** [damiankorcz/Prism-Theme#4]
Loving the theme; it's nice and compact, just the way I like it, but it appears to have some conflicts with the Obsidian Tabs plugin.

![image](https://user-images.githubusercontent.com/93364935/139941864-d26aedf8-3f10-4749-8f94-54cf75df87b7.png)

As you can see, the tab row is cut off.

Is there a configuration option that will correct this or is this a bug in Obsidian Tabs?

**Comment by damiankorcz** [comment]
Hi @MalignantCarp,
I've decided not to support this plugin at the moment due to some technical issues I've encountered and since the plugin hasn't been updated in over 11 months. My apologize for the extremally late reply and for dropping this feature request.
