### ISSUE TITLE
Feature Request: Hiding title bars for more focused work and gaining screen real estate

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#40]
Would you consider adding a toggle for hiding title bars of the notes automatically? I've seen example use cases in Minimal and Shimmering Focus themes.

**Comment by chrisgrieser** [comment]
:carrrl:

**Comment by damiankorcz** [comment]
Hi @yigitozgumus,
With the release of v2.0.0, you can now toggle on Note Titlebar hiding (Go to Style Settings -> Prism Theme -> Feature Toggles -> Hide Note Titlebar).

Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating.

Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
