### ISSUE TITLE
Too much indentation of first line of untyped code block in Reading mode

### ISSUE THREAD

**Issue by claremacrae** [damiankorcz/Prism-Theme#42]
Lots of my code blocks don't have a language specified. When I preview them, the first line is indented slightly.

For example, this:

    ```
    2021-05-05
    today
    tomorrow
    next monday
    last friday
    in two weeks
    ```

... looks like this:

![image](https://user-images.githubusercontent.com/4840096/157955775-a6f084ee-7ae4-4357-8e19-89526fdb8d55.png)

### Environment

- Obsidian 0.13.33
- Installer 0.12.15
- Appearances
    - Prism v1.5.2
    - No snippets
- Plugins
    - Style Settings 0.4.10
- OS: macOS, iPhone

### Workaround

Specify language type:

    ```text
    2021-05-05
    today
    tomorrow
    next monday
    last friday
    in two weeks
    ```

Gives:

![image](https://user-images.githubusercontent.com/4840096/157956708-14903dae-1dc7-4116-a588-013ab19aa7ba.png)

Except that I've quite grown to like text snippets standing out in red!

**Comment by claremacrae** [comment]
> Except that I've quite grown to like text snippets standing out in red!

One reason I quite like code blocks being red is that it is consistent with how Prism display inline code - between back-ticks:

![image](https://user-images.githubusercontent.com/4840096/157959191-1409b88d-35fa-44a0-bddb-0b1fbd4a53ad.png)

**Comment by damiankorcz** [comment]
Hi @claremacrae ,
With the release of v2.0.0, this issue should be resolved.

Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating.

Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
