### ISSUE TITLE
Tag folder plugin and prism 

### ISSUE THREAD

**Issue by meeffe** [damiankorcz/Prism-Theme#43]
Hi,
Tag folder plugin in connection with prism theme gets some unexpected glitches like the ones here - 
![image](https://user-images.githubusercontent.com/94453502/160485051-0b23709e-8143-4828-b3a6-676cd028c8fe.png)
https://github.com/vrtmrz/obsidian-tagfolder

Any change to fix it?

świetny szablon!

**Comment by damiankorcz** [comment]
Hi,
It will be fixed in an upcoming update.

![image](https://user-images.githubusercontent.com/7290097/160485863-5137d0c9-be6d-4e03-8898-6ebb961d2843.png)

Dzieki ;)

**Comment by meeffe** [comment]
@damiankorcz tak przy okazji, bo nie znalazłem. można jakoś kolorować / zmieniać wygląd tagów w tym szablonie, żeby były bardziej widoczne?

**Comment by damiankorcz** [comment]
> @damiankorcz tak przy okazji, bo nie znalazłem. można jakoś kolorować / zmieniać wygląd tagów w tym szablonie, żeby były bardziej widoczne?

W dostępnej wersji nie ale mam zamiar to poprawić w nowej.

**Comment by damiankorcz** [comment]
Z aktualizacją v2.0.0, Tag Folder powinien wyglądać poprawnie. Tag'i są teraz bardziej widoczne w tej aktualizacji. Po aktualizacji musisz zresetować ustawienia w Style Settings i odpalić Obsidian ponownie.

Tutaj są notatki z aktualizacji v2.0.0: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0
