### ISSUE TITLE
Feature Request: Option to remove borders for embedded pages and blocks

### ISSUE THREAD

**Issue by yigitozgumus** [damiankorcz/Prism-Theme#44]

**Comment by AiurArtanis** [comment]
u mean this?
![image](https://user-images.githubusercontent.com/98091664/160760199-6b11fb62-2a2d-4eb1-ae07-22f93f8b4aa9.png)
if so, it can be customized by **Style-Setting** plguin as listed below:
![image](https://user-images.githubusercontent.com/98091664/160760444-ffbee9fd-71ab-47e2-ab5e-2907dfc2d70c.png)

**Comment by yigitozgumus** [comment]
Hello, I may have used the wrong term for this. I mean the embedded pages and blocks that we put in pages using !

![[SomePage]]

![[SomePage#Some Header]]

Border around this pages can be optionally disabled for more clean look (my opinion of course, theme is already has a clean approach for things :) )

![image](https://user-images.githubusercontent.com/5840669/160779710-795187bd-9946-4db4-a456-c137c422c653.png)

**Comment by AiurArtanis** [comment]
> Hello, I may have used the wrong term for this. I meant the embedded pages and blocks that we put in pages using !
> 
> ![[SomePage]]
> 
> ![[SomePage#Some Header]]
> 
> Border around this pages can be optionally disabled for more clean look (my opinion of course, theme is already has a clean approach for things :) )

i get it now. in fact i have the opposite view upon this border because it's easier to distinguish the editor and embedded pages in my opinion. but i applaud for this issue to add an option to cusomize this border. ;-）

**Comment by yigitozgumus** [comment]
Thanks, I think I saw a similar approach in the Shimmering Focus theme but borders are visible only in edit mode. So in edit mode, we could get that distinction and borderless embed can only be activated for the preview mode.
