### ISSUE TITLE
[FR] Obsidian Publish Theme

### ISSUE THREAD

**Issue by etsploit** [damiankorcz/Prism-Theme#47]
Would really love to see this theme adapted for use with Obsidian Publish

**Comment by damiankorcz** [comment]
Hi @etsploit,
It's still on the list. I'll have to figure out how to handle things with different styles and colour options. No set timeline for this yet. Currently have plenty to work on supporting Desktop and now newly added Mobile. I'll consider this once there is more demand for it.

**Comment by RhymeRequiem** [comment]
I would also be interested a Prism theme for Obsidian Publish.

**Comment by damiankorcz** [comment]
I don't see myself doing this anytime soon if ever so for now I'm closing this feature request.

**Comment by jvican** [comment]
Oh, this is a pity, it would be absolutely amazing if there was a theme to use with Obsidian Publish!
