### ISSUE TITLE
File Explorer Font Size

### ISSUE THREAD

**Issue by ackstorm23** [damiankorcz/Prism-Theme#48]
When using your theme, the File Explorer's font size appears to be 'fixed' such that I cannot change it.

With Control+ and Control- I can increase and decrease the font size for everything else,  but not that. 

Do you encounter this too? I cannot find the cause or a way to increase my font size for the File Explorer pane.

**Comment by damiankorcz** [comment]
Hi @ackstorm23,
It's possible that the issue exists in v1.5.2. I've just released v2.0.0 today and I don't seem to have the issue you describe. 

![Obsidian_2022-04-26_01-28-01](https://user-images.githubusercontent.com/7290097/165195540-94788ce1-bc20-4418-a908-562ae0fa7983.gif)

Make sure to reset your Style Settings and restart Obsidian for the theme to work correctly after updating to v2.0.0.

Here are the release notes for the v2.0.0 update: https://github.com/damiankorcz/Prism-Theme/releases/tag/2.0.0

**Comment by ackstorm23** [comment]
No, I updated to v2 before posting this.    I've also restarted obsidian to make sure.  I also turned off community plugins but still the file explorer refuses to change size. 

I must be running into a bug with Obsidian.  Thanks for verifying.

**Comment by damiankorcz** [comment]
@ackstorm23 Are you running the latest Installer version? You can see the version in the About section in the settings under your Current Version. Latest installer should be 0.14.6. To update it you just have to re-download Obsidian from the main website ( https://obsidian.md/ ) and run it. It should update the installer.

**Comment by ackstorm23** [comment]
Yes 

```
|SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.5
	Operating system: #1 SMP Fri May 21 00:10:17 CEST 2021 5.11.4-1-rt11-MANJARO
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Safe mode: on

RECOMMENDATIONS:
	none
```

**Comment by ackstorm23** [comment]
I posted on the official forums about it.   Since it's clearly not restricted to your theme, go ahead and close this. 

https://forum.obsidian.md/t/unable-to-change-file-explorer-font-size/36497

**Comment by damiankorcz** [comment]
Got it. Good luck getting it resolved!
