### ISSUE TITLE
Sliding Pane style problem

### ISSUE THREAD

**Issue by reorx** [damiankorcz/Prism-Theme#49]
Great theme! I'm using Sliding Pane plugin, the border of the vertical panes is a bit weird. Is it normal? 

![image](https://user-images.githubusercontent.com/405972/165208013-097091d1-31c1-4552-afce-0cc9896dee83.png)

**Comment by damiankorcz** [comment]
Hi @reorx, that definitely isn't supposed to look like that. I'll look into fixing it. Thanks for reporting!

**Comment by damiankorcz** [comment]
@reorx I've just pushed an update that should remove the shadows and look correctly.

**Comment by reorx** [comment]
Amazing speed! I just updated the theme and it looks beautiful, thanks for the support!
