### ISSUE TITLE
BUG: cursor displays wrong in Hover Editor popup window

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#50]
@damiankorcz 

## BUG

cursor cannot display in correct line in **Prism Theme** with **Hover Editor** popup window

https://user-images.githubusercontent.com/98091664/165210729-d95456ab-9539-4137-8ebe-95c7c75bea12.mp4

_popup window in **Prism** and default theme_

(it seems my screen recording app doesn't suit GitHub well, but u can download this video normally)

## Environment

os: Win 10
ob: v0.14.6
Prism: v2.0.0
Hover Editor: v0.8.7

## Last

in fact, this bug appears before v2.0.0 released, and the first time i found this bug is about Feb (maybe the first **Hover Editor**  released version).

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, this issue should be resolved now. I've used scaling for the popovers to set the view to 90% which was causing the misalignment. I've now removed that so the text should be the usual size and it should work as intended.

**Comment by AiurArtanis** [comment]
> Hi @AiurArtanis, this issue should be resolved now. I've used scaling for the popovers to set the view to 90% which was causing the misalignment. I've now removed that so the text should be the usual size and it should work as intended.

so will it fixed on next version?

**Comment by damiankorcz** [comment]
@AiurArtanis It should already be fixed. I pushed the fix without doing a new theme version.
