### ISSUE TITLE
Callouts blocks rendering

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#52]
@damiankorcz hello again

## BUG

tables in **Callout** block are rendered wrong in **Prism** like this:
![image](https://user-images.githubusercontent.com/98091664/166851826-3a24faec-b598-428b-8918-0cde8d6ba5d9.png)

it's rendered in default theme:
![image](https://user-images.githubusercontent.com/98091664/166851972-eba30ddc-074a-4a52-a6ee-c64ba6604a89.png)

## FR

and there's another question that i customize **Callouts** block style by plugin **Admotions**, but they are restyled in **Prism**:
![image](https://user-images.githubusercontent.com/98091664/166852961-44f6ae14-b242-4948-86dd-ec7066c9f4ed.png)
_in Prism theme_

![image](https://user-images.githubusercontent.com/98091664/166853170-a32c1f48-e13b-47e6-83dd-25accc1fb3ce.png)
_in defalut theme_

(i also find u define some **Callouts** types in theme css, and those which not defined are rendered with black border)

so would u please add an option to open/close **Callouts** rendering in **Style Setting** - Prism theme - Feature toggles?

## Environment

OS: win10
OB: v0.14.6
Prism: v2.0.0

## Last

hope for your reply asap 😁

**Comment by AiurArtanis** [comment]
emmm, and it seems there's something wrong in Style Setting:
![image](https://user-images.githubusercontent.com/98091664/166853709-ac68f03c-f5aa-4363-a590-9090afb674a7.png)

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, I'll have the spacing inside the callout fixed for the next update. As for Admonitions, I've had a quick look and I might be able to adapt the colour you select for your custom Callout and style it in the same way as the default ones so it matches the style. Will look into it more tomorrow. Thanks for reporting!

**Comment by damiankorcz** [comment]
Hi @AiurArtanis, the top padding should now be resolved in v2.1.0. I'll close this issue in place of issue #54 since it's specific for the second issue. So you can track progress of that there.
