### ISSUE TITLE
Adjust selected text background color

### ISSUE THREAD

**Issue by fncll** [damiankorcz/Prism-Theme#53]
I am currently using Prism (Light, Swan settings) and have one issue I can't figure out: where/how can I adjust the color of the background of selected text? As you can see from this image, where the first sentence is selected, the selection is very low contrast:

![CleanShot 2022-05-05 at 09 09 42](https://user-images.githubusercontent.com/1208889/166966221-2584568a-cd96-4898-b5a0-520cd2d70b36.png)

Thanks in advance!

**Comment by damiankorcz** [comment]
Hi @fncll, this fix should now be available in v2.1.0.
