### ISSUE TITLE
Support plugin "Quiet Outline"

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#58]
@damiankorcz hello again

## Plugin

**Quiet Outline** is an enhanced outline plugin.
[quiet outline](https://github.com/guopenghui/obsidian-quiet-outline)

would u please make **Prism** suit this plugin ?
![image](https://user-images.githubusercontent.com/98091664/167401479-0d70f038-fd31-4e77-9f6d-ab0b49e44ef5.png)

## Environment

OS: win10
OB: v0.14.6
Prism: v2.1.0
Quiet Outline 0.2.4

## Last

😁

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.2.0.
