### ISSUE TITLE
Contrast issue with drop-down menus (Light, Swan)

### ISSUE THREAD

**Issue by fncll** [damiankorcz/Prism-Theme#60]
Hello, similar to my previous issue, here is what drop-down menus look like using Prism, Swan, Light theme (Projects is selected/highlighted in the example):

![CleanShot 2022-05-09 at 12 02 32](https://user-images.githubusercontent.com/1208889/167479502-597a3407-3fd3-47ee-9a43-94023043f72a.png)

Any chance you can adjust this in a future release? Thanks!

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.2.0.
