### ISSUE TITLE
[FR] Change selected text contrast - Pine

### ISSUE THREAD

**Issue by DutchPete** [damiankorcz/Prism-Theme#61]
In dark mode I am using the Pine theme (I love it), but selecting text needs a higher contrast, while the global search box could also do with a background color change.

**Comment by damiankorcz** [comment]
Hi @DutchPete,
Please use the template provided in future Feature Requests / Issues.

**Comment by DutchPete** [comment]
Done: #63

**Comment by damiankorcz** [comment]
Thanks! Issue followed on : #63
