### ISSUE TITLE
[FR] Customizable Colors for Bold and Italic fonts 

### ISSUE THREAD

**Issue by Felipe-Juan** [damiankorcz/Prism-Theme#62]
Similar to the options they have for Headings 1 to 6, but for bold and italics

**Comment by damiankorcz** [comment]
Hi @Felipe-Juan,
Please use the template provided in future Feature Requests / Issues.

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.2.0. I've added Colour options in Style Settings for Bold / Italic Text and Internal / External Links (Style Settings ➜ Prism Theme ➜ Editor ➜ Editor Text Color).
