### ISSUE TITLE
[FR] Dark mode: enhance contrast text selection and global search box

### ISSUE THREAD

**Issue by DutchPete** [damiankorcz/Prism-Theme#63]
**Is your feature request related to a problem? Please describe.**
Text selection and global search box activation are not clear in dark mode - Pine version.

**Describe the solution you'd like**
A better contrast

**Describe alternatives you've considered**
Using a snippet.

**Additional context**

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.2.0.

**Comment by DutchPete** [comment]
I am happy with the global search box, not quite with the text selection. I understand that you have to strike a balance between your various users, so I will not push this.

What I would like to do is add a snippet at my end to change the color slightly. Can you tell me what elements I should choose?

If I am not mistaken it is this one: `.theme-dark.pt-color-scheme-pine-dt {`
modified with this:  `--background-primary-alt: hsl(135 35% 15.5%)`

Correct?

**Comment by damiankorcz** [comment]
Hi @DutchPete,
To just change the colour of the text selection you can do the following:
```css
.theme-dark.pt-color-scheme-pine-dt {
    --text-selection: red;
}
```
Change `red` to any CSS compliant colour value (RGB, HEX, HSL, etc).

**Comment by DutchPete** [comment]
Hi @damiankorcz thanks a lot, that works fine.
Issue can be closed.
