### ISSUE TITLE
[Bug] Part of the name still appears with "Hide Note Titlebar" on Mobile 

### ISSUE THREAD

**Issue by Felipe-Juan** [damiankorcz/Prism-Theme#65]
**Describe the bug**
![Screenshot_20220515-080902_Obsidian.jpg](https://user-images.githubusercontent.com/85803620/168469887-cc5e85d2-9918-484c-a927-c661f0dc8bf1.jpg)

Does not disappear the page name entirely after activating "Hide Note Titlebar". It only happens on Mobile.

**To Reproduce**
With the Styles Settings plugin installed, search for "🪠 Feature Toggles" in Prism Theme and enable Hide Note Titlebar.

**Expected behavior**
It's just a line with nothing written, like on a computer.

**Screenshots**
https://user-images.githubusercontent.com/85803620/168470466-06bbaae6-797a-46e8-9d44-d74b4d05f386.mp4

**Setup Information**
 - Device Type: Smartphone Android
 - Operating System: Android 11 | LineageOS 18.1
 - Prism version: v2.1.1
 - Color Schemes Used: Mocha
 - Obsidian Version: 1.2.0

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.3.0.
