### ISSUE TITLE
[FR] It's very hard to find you cursor if you are a vim user within obsidian. 

### ISSUE THREAD

**Issue by ancion** [damiankorcz/Prism-Theme#67]
The color of cursor is too same as background, It's very hard to find it when you move it fast with vim way. Hope to add more hightlight feature for vim user. 

**Add hightlight feture in setting or make cursor backgroud different.**

**Comment by damiankorcz** [comment]
There are some improvements to Vim mode coming up in the next update. See this comment: https://github.com/damiankorcz/Prism-Theme/issues/59#issuecomment-1122756126

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.2.0.
