### ISSUE TITLE
[FR] File Tree Alternative Plugin Support

### ISSUE THREAD

**Issue by RhymeRequiem** [damiankorcz/Prism-Theme#69]
**Is your feature request related to a problem? Please describe.**
I'm interested in "File Tree Alternative Plugin" becoming officially supported by Prism.

**Describe the solution you'd like**
It looks off when currently used with Prism. The biggest thing that bugs me is the background for the bar with the "Create folder" and sort options. The division between the two panels (folder view and note view) and the font size could be specifically improved upon as well.

**Describe alternatives you've considered**
I do not have the knowledge or ability to add support myself, whether that be through here or through snippets.

**Additional context**
None. Thank you for any consideration.

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.3.0. I'll explore further improvements in the future, specifically the position and alignment of the Nav Buttons such that it reflects the options selected in Style Settings.
