### ISSUE TITLE
Quick Explorer Top Bar offset

### ISSUE THREAD

**Issue by MalignantCarp** [damiankorcz/Prism-Theme#7]
There's something going on with the back/forward button area as well in combination with the Quick Explorer plugin.

![image](https://user-images.githubusercontent.com/93364935/140086303-7b5ea779-f893-4ce7-83f4-8d7f0fc6698e.png)

Vs the default theme:

![image](https://user-images.githubusercontent.com/93364935/140086486-02f85e9a-465c-4226-ace2-37431a1ccb50.png)

**Comment by damiankorcz** [comment]
@MalignantCarp Should now be addressed in version 1.1.0. The whole plugin should now be theme correctly.
