### ISSUE TITLE
[FR] Right sidebar improvement

### ISSUE THREAD

**Issue by AiurArtanis** [damiankorcz/Prism-Theme#71]
@damiankorcz 

## FR
could u please remove the vertical spacing in right sidebar?

**Is your feature request related to a problem? Please describe.**
it seems there's no any theme supporting this feature and i was wondering if the Obsidian Editor cannot support this in underlying logic.

**Describe the solution you'd like**
Add an option to make right sidebar align to window in **Style-setting**-Prism Theme-User Interface

**Describe alternatives you've considered**
i draw a porto diagram as listed below.(maybe redesigning the expand/collapse button will be better?)

**Additional context**
![image](https://user-images.githubusercontent.com/98091664/172540523-b2b8b62f-a69a-4bdc-893e-9d7ada9a79b6.png)
_right sidebar displayed now_
↓↓↓
![image](https://user-images.githubusercontent.com/98091664/172540253-224ddb9c-0c6e-4169-ae5c-aed1f629c6ed.png)
_when remove the spacing_

## Last
i just update Prsim v2.1.1 and very glad to see **Quiet-Outline** supported, thank u

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.3.0. You can find the option in Style Settings ➜ Prism Theme ➜ User Interface ➜ Sidebar Elements ➜ Minimal Right Sidebar.
