### ISSUE TITLE
[FR] tighten line spacing for line-wrapped headings

### ISSUE THREAD

**Issue by Lx** [damiankorcz/Prism-Theme#72]
**Is your feature request related to a problem? Please describe.**
Some of my notes' headings span multiple lines on my small mobile device.  The space between those lines looks wrong (too large).  For example, there is more space between line 1 and line 2 of the heading than there is between the (entire) heading and the following body text.

**Describe the solution you'd like**
Ideally the theme's CSS would be altered to reduce the `line-height` for headings compared to that for body text.

**Describe alternatives you've considered**
* I looked for but could not find a related setting in Style Settings.
* I looked for but could not find any obvious way (as a novice Obsidian user) to override heading line height globally.

**Comment by damiankorcz** [comment]
This should now be addressed in Version 2.3.0.

**Comment by Lx** [comment]
It's perfect now.  Thank you, @damiankorcz.
