### ISSUE TITLE
[FR] Rotatable Titlebar Header

### ISSUE THREAD

**Issue by DxYz1** [damiankorcz/Prism-Theme#76]
It would be great if the titlebar for a note could be rotated, just like it can be with the sliding panes plugin.

**Comment by damiankorcz** [comment]
Hi @DxYz1,
With Obsidian 1.0.0 there is now a Stack Tabs feature which is a native implementation of the Sliding Panes Plugin. The latest 3.0.0 version of Prism supports it.
https://help.obsidian.md/User+interface/Stacked+tabs

Let me know if that would satisfy this feature request or if you mean something else.
