### ISSUE TITLE
[Bug][Code block] Some texts are hard to read in live view

### ISSUE THREAD

**Issue by np-22** [damiankorcz/Prism-Theme#77]
Python code block
```python
def romanToInt(self, s: str) -> int:
	res, prev = 0, 0
	dict = {'I':1, 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}
	for i in s[::-1]:          # rev the s
		if dict[i] >= prev:
			res += dict[i]     # sum the value iff previous value same or more
		else:
			res -= dict[i]     # substract when value is like "IV" --> 5-1, "IX" --> 10 -1 etc 
		prev = dict[i]
	return res
```

Live view
<img width="794" alt="image" src="https://user-images.githubusercontent.com/10591164/180130678-cd18188d-ca1f-4d23-8575-7225d4ec6cf7.png">

Reading view
<img width="809" alt="image" src="https://user-images.githubusercontent.com/10591164/180130753-6358137c-511d-49c4-a7dd-644a6815f071.png">

**Comment by damiankorcz** [comment]
Hi @np-22,
Syntax Highlighting and Colours have been redone in the latest 3.0.0 update which should address this issue.
