### ISSUE TITLE
Links are bold in Reading mode but normal in Editing mode

### ISSUE THREAD

**Issue by ShahriarKh** [damiankorcz/Prism-Theme#78]
Links are bold when I'm in the Reading mode, but have normal weight when I'm in the editing mode. Here's an example:

Editing:
![image](https://user-images.githubusercontent.com/31452340/180420242-a37f4de3-48bb-4ece-baf5-14c00c2ed988.png)

Reading:
![image](https://user-images.githubusercontent.com/31452340/180420267-eeb63ce0-6bb9-4265-8508-aad510232f03.png)

And this is where the style is being applied:
`font-weight: 600`
![image](https://user-images.githubusercontent.com/31452340/180420578-177b4dd8-0e57-4f76-ab6d-a691daf31a34.png)

I can't seem to find an option to disable bold links.

My font is Balsamiq sans if it helps.

**Comment by damiankorcz** [comment]
Hi @ShahriarKh,
The links are no longer bold in the newest 3.0.0 update and should be consistent through all editor modes.
