### ISSUE TITLE
Advanced Tables toolbar buttons can't be used

### ISSUE THREAD

**Issue by ped22** [damiankorcz/Prism-Theme#8]
Advanced tables is only partially functional.

It can be used OK, except for the toolbar.

The icons in the toolbar do nothing when they are clicked. There are not even mouse over effects that indicate they are clickable buttons.

Running those commands from the command palette function fine.

Using Obsidian v0.12.19
Prism v1.0.0
Advanced Tables v0.13.0

**Comment by damiankorcz** [comment]
@ped22 Should now be addressed in version 1.1.0
