### ISSUE TITLE
[Bug] Unable to change color of unresolved nodes

### ISSUE THREAD

**Issue by github-jake** [damiankorcz/Prism-Theme#81]
Hello, I am unable to change the color of unresolved note's nodes when using dark mode. Both presets and custom colors do not work. To illustrate this I set every color option to yellow. As you can see the unresolved nodes do not change. Are you able to replicate this?

**Light mode**

![image](https://user-images.githubusercontent.com/68354689/180582383-d3e7bd31-b015-4b19-a485-245ff7c77146.png)

**Dark mode**

![image](https://user-images.githubusercontent.com/68354689/180582482-95eedd51-baf9-4970-b246-1e34a1481f28.png)

**To Reproduce**
Style settings plugin -> Prism Theme -> Appearance -> Graph Color Customization -> Dark Theme -> Graph Unresolved Color -> Graph Unresolved Color Presets -> Change Color -> Restart -> No Color Change

**Setup Information**
PC
Pop! OS 22.04 LTS
Prism v2.3.0
Raven Color Scheme
Obsidian v0.15.8
Installer v0.15.8

Besides this, I appreciate you creating this theme, it is my favorite so far :)

**Comment by damiankorcz** [comment]
Hi @github-jake,
This should now be resolved in version 3.0.0.
