### ISSUE TITLE
[Bug] Obsidian Commander page header commands render as filled in square

### ISSUE THREAD

**Issue by mcala** [damiankorcz/Prism-Theme#82]
**Describe the bug**
Hello! Using the Prism theme with the [obsidian-commander plugin](https://github.com/phibr0/obsidian-commander), but icons added to a note's _page header_ do not show up properly.

**To Reproduce**
1. Install the obsidian-commander plugin
2. Add a command to the page header
3. The icon for the added command renders as a filled in square rather than the icon itself

**Expected behavior**
The icon would appear and behave like the "Current View", "Close Note", and "More Options" icons.

**Screenshots**
[Screen Shot 2022-08-03 at 08.33.38.pdf](https://github.com/damiankorcz/Prism-Theme/files/9251300/Screen.Shot.2022-08-03.at.08.33.38.pdf)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS 12.4
 - Prism version: 2.3.0
 - Color Schemes Used: Swan + Mint Accent, have tested other combinations and all appear the same way
 - Obsidian Version: 0.15.9
 - Obsidian Installer Version: 0.14.6
 - Related Community plugins: Tested with all community plugins turned off except Style Settings and Obsidian-Commander. 

**Additional Context**
The added commands work with other themes (tested: Minimal, California Coast, Primary, Default) which is why I'm submitting the bug report here rather than to obsidian-commander.

**Comment by damiankorcz** [comment]
Hi @mcala,
This should no longer be an issue since starting with Prism 3.0.0, custom icons are no longer used.
