### ISSUE TITLE
[Bug] Trello and Bartender Plugin Issues

### ISSUE THREAD

**Issue by OrangeWithEyes** [damiankorcz/Prism-Theme#83]
[Please fill out the following sections as best you can to help diagnose the issue. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the bug.]

**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[ Steps to reproduce the behavior:
4. See error ]

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots/GIFs/Videos to help explain your problem]

**Setup Information**
 - Device Type: [e.g. Phone/iPhone, Tablet/iPad, PC/Mac]
 - Operating System: [e.g. Windows 10/11, MacOS Big Sur, Fedora/Arch, Android/iOS, etc.]
 - Prism version: [Found in Settings -> Top Left Corner]
 - Color Schemes Used: [Found in Settings -> Style Settings tab -> Prism Theme -> Appearance -> Accent, Color Schemes and Style -> Light/Dark Theme -> Color Scheme]
 - Obsidian Version: [Found in Settings -> About tab]
 - Obsidian Installer Version: [Found in Settings -> About tab]
 - Related Community plugins: [If any list the plugins you think might be related to your issue. Found in Settings -> Community Plugins -> Installed plugins (Ones that are enabled when the bug occurs)]

**Additional context**
[Add any other context about the problem here]

**Comment by OrangeWithEyes** [comment]
Ok i'm really dumb sorry about that lol

What i meant to say was that Prism has a slight appearance incompatibility with both the beta plugin Bartender, and the plugin Obsidian Trello. These are the visual issues:
![61e8be82e411751efab9e4d855df1340](https://user-images.githubusercontent.com/107226100/184557503-08849a6a-babc-4efa-9d50-805eaa00d976.png)
![0382f471f047c108c38fc5ac7f4c603d](https://user-images.githubusercontent.com/107226100/184557505-2b6b8452-0f0e-4fbf-9947-68aa655b4c56.png)

In the first image, the fourth icon (which is part of Bartender) allows you to reorder folders and notes. Although it still functions, it's weirdly angled up.
In the second image, you can see that Obsidian Trello (which i censored for privacy reasons) gets absolutely messed up by Prism, with weird bars instead of checkmarks (that I can't click well), icons at the top being over "Today" and weirdly sized, and the progress bar being really off.

I understand that these are small issues with small plugins, but if you have the time to fix them, I'd appreciate it a lot :)

**Comment by damiankorcz** [comment]
Hi @OrangeWithEyes,
Sorry for getting back to you this late.

I've had a look at the Bartender plugin and I don't really know where to look for the 3 line menu icon. Is this still part of the plugin?

As for the Trello plugin, the nav header should be styled correctly since the big rewrite (version 3.0.0+). Can you give me feedback on the other elements again. I'm not very familiar with the plugin and not really sure how to use it correctly.
