### ISSUE TITLE
Hide unnecessary interface elements with Style Settings [FR]

### ISSUE THREAD

**Issue by nttldnknwn** [damiankorcz/Prism-Theme#84]
Hello!

I do not feel comfortable working in programs whose interface is littered with different graphic elements, responsible for different functions that I do not even use.
I want to optimize my workspace so that it contains only the functions that I use and nothing unnecessary.

I would like the Style Settings plugin to allow you to disable the following interface elements for the Prism theme:
- File Explorer Icon
- New File Icon
- New Folder Icon
- Change Sort Order Icon
- Current View (Read / Edit) Icon
- Close Icon
- More Options Icon
![1](https://user-images.githubusercontent.com/106082291/185061099-efc55171-14f5-4d14-aa40-88711a0185fd.png)

As an alternative solution, I considered:
- **Hider Plugin**. 
It does not allow you to hide these elements
- **Style Settings → Feature Toggles → Hide Note Titlebar**
I managed to hide Current View (Read / Edit) Icon, Close Icon and More Options Icon with this function, but other unwanted interface elements are still there, which I do not like =(

Thank you so much and have a great day!

_(And it would also be useful to be able to disable the Note Titlebar from popping up when hovering over the top of the workspace.)_

**Comment by damiankorcz** [comment]
Hi @nttldnknwn,
Prism doesn't really aim to hide elements of the UI but instead exaggerate them for increased clarity. I don't intend on implementing the suggested features. You might find another theme such as [Shimmering Focus](https://github.com/chrisgrieser/shimmering-focus) better for your needs. It specifically puts more focus on this type of minimalism.
