### ISSUE TITLE
[FR] Indentation Guides not available in Prism Live Preview mode

### ISSUE THREAD

**Issue by mbentley** [damiankorcz/Prism-Theme#85]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is a bug or an intended styling but the `Editor` > `Show Indentation Guides` setting doesn't have an effect when it is toggled on when the user is in Live Preview mode.  No indentation guides are shown with Prism.

![screenshot 2022-08-30 at 12 28 51 PM](https://user-images.githubusercontent.com/414445/187491243-25da5d1f-3ed0-494d-9f81-1e9ba90c8c8b.png)

Live Preview:
![screenshot 2022-08-30 at 12 33 29 PM](https://user-images.githubusercontent.com/414445/187491398-42eeced0-9452-48d8-b22f-7def2c7e2e27.png)

Reading:
![screenshot 2022-08-30 at 12 33 53 PM](https://user-images.githubusercontent.com/414445/187491475-49c0d4c7-6f75-4735-9d5e-5b21f7ea5aa7.png)

**Describe the solution you'd like**
It would be ideal if Prism could show indentation guides in live preview/edit mode.

**Describe alternatives you've considered**
I've tried to look to see if I could force these on through CSS and it looks like there is this that is preventing them from showing:

```
.markdown-source-view.mod-cm6 .cm-indent::before {
    border-right: none;
}
```

I was able to work around this, at least for myself, with a CSS snippet but I don't know if this might break anything else as I haven't very widely tested it:

```
.markdown-source-view.mod-cm6 .cm-indent::before {
  border-right: 1px solid var(--indentation-guide);
  margin-left: 2px;
}
```

I also added the `margin-left` to try to center is under the bullet; probably a better/more reliable way to do that.

**Additional context**
n/a

**Comment by damiankorcz** [comment]
Hi @mbentley,
This issue should be resolve in the 3.0.0 update.
