### ISSUE TITLE
Status Bar Always Changes to Floating on Startup of Obsidian

### ISSUE THREAD

**Issue by DxYz1** [damiankorcz/Prism-Theme#86]
I changed the status bar style to "Fixed" in style settings, but every time I open Obsidian the status bar changes to floating. I'm using the most recent insider build of obsidian on macOS Monterey.

**Comment by damiankorcz** [comment]
Hi @DxYz1,

I've just checked for this issue on the latest version of the theme, and I can't seem to replicate it. If you happen to be coming from the non-insider version of Obsidian and updated the theme right after the transition, there is a change that it's an issue with Style Settings and option variables changing names. If that is the case, I would highly recommend resetting Style Settings for Prism to default and restarting Obsidian. Sorry for the inconvenience. Also, I've just pushed a new Beta version (7) of the theme so you can check beforehand if that happens to resolve your issue.

Just a word of warning, although the theme is almost ready for 0.16.0+, it has been fully rewritten for it and I'm still working on finalising certain aspects of the design and features. If you encounter any major breaking issues, I'd recommend sticking to the default theme until Prism 3.0.0 is officially out.

**Comment by DxYz1** [comment]
@damiankorcz thanks for checking this out. I updated the newest version of Prism and haven't experience this issue.

**Comment by damiankorcz** [comment]
Hi @DxYz1,
That's good to hear. Thanks for reporting it regardless! I'll close this issue now.
