### ISSUE TITLE
[FR] Please add frontmatter highlighting

### ISSUE THREAD

**Issue by aquatix** [damiankorcz/Prism-Theme#88]
**Is your feature request related to a problem? Please describe.**
I extensively use frontmatter in my notes for things like creation date, tags, aliases and more, and I miss syntax highlighting in Prism.

**Describe the solution you'd like**
A simple colour distinction between 'key' and 'value' would be great.

**Describe alternatives you've considered**
I tried finding settings for this in Style Settings and in the source code of the theme, but did not find it. 

For example, the Primary theme has a section in its css file 'YAML/Metadata' with relevant theming.

**Additional context**
I'll add a small screenshot from Primary just to show what I mean.

**Comment by aquatix** [comment]
![Screenshot from 2022-10-13 16-39-10](https://user-images.githubusercontent.com/629545/195627623-16d0c09a-99e1-4613-8d86-dcc8ff37c061.png)

**Comment by aquatix** [comment]
I went creative and created a snippet with some styling that went well with the dark Mocha theme of 3.0.0 beta: https://gist.github.com/aquatix/82f8df145ae77a1160f58d894ddb7791

**Comment by damiankorcz** [comment]
Hi @aquatix,
I've implemented some highlighting for the frontmatter in the new final 3.0.0 release.

**Comment by aquatix** [comment]
Great, thanks! Can't wait for it to show up in my Obsidian installs, it seems it hasn't registered yet as update there.

**Comment by damiankorcz** [comment]
@aquatix Yeah sometimes it takes some time. You can uninstall and install it again and it should come through.

**Comment by aquatix** [comment]
Ah, for some reason it thinks the -beta11 is newer. After doing the uninstall dance it's there, thanks! Looking tidy, great job on the update.
