### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gabiam20** [damiankorcz/Prism-Theme#89]
**Describe the bug**
Hi, I updated the plugin to version 0.4.12 and now I can't write a title more than 2 lines in callout and even with 2 lines the callout stay very tight. Before I update I could write 3 or more lines.

**Screenshots**
2 lines:
![image](https://user-images.githubusercontent.com/115800036/195860106-436b1152-9029-468e-bfb7-07b3eb82d69d.png)

3 lines:
![image](https://user-images.githubusercontent.com/115800036/195860219-abbe5216-846b-4de5-be20-3a3f8914c37e.png)

**Comment by damiankorcz** [comment]
This will be fixed in the next 3.0.0 Beta release. Thanks for reporting!

**Comment by gabiam20** [comment]
thanks! :)
