### ISSUE TITLE
[Bug] Text Cursor is overlapped by the Mobile Toolbar when editing a few lines lower than the initial start

### ISSUE THREAD

**Issue by huayins** [damiankorcz/Prism-Theme#90]
The flashing cursor will be blocked by the toolbar and input method panel in the input interface, with the increase of text.
This is the problem I encountered when using this theme in Android.

I like this theme very much. I hope the boss can solve this problem.

**Comment by huayins** [comment]
The situation remains the same
Look at the video





---Original---
From: "Damian ***@***.***&gt;
Date: Tue, Dec 6, 2022 06:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [damiankorcz/Prism-Theme] Feedback questions (Issue #90)




 
Hi @huayins,
 Can you check if this is still the case with the latest update, 3.1.0. Also, please provide a screenshot or recording if you are still having this issue.

**Comment by damiankorcz** [comment]
Hi @huayins,
It appears that the video you tried to embed didn't embed. You might have to do it on GitHub directly instead of the email reply.

**Comment by huayins** [comment]
https://user-images.githubusercontent.com/115480057/206247589-41ddad31-8d01-4cb1-be3b-8e286d0c69b9.mp4

**Comment by damiankorcz** [comment]
Hi @huayins,
This issue should now be addressed in version 3.2.0.

**Comment by huayins** [comment]
Yes, it's great



---Original---
From: "Damian ***@***.***&gt;
Date: Fri, Jan 13, 2023 05:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [damiankorcz/Prism-Theme] [Bug] Text Cursor is overlapped by theMobile Toolbar when editing a few lines lower than the initial start (Issue#90)




 
Hi @huayins,
 This issue should now be addressed in version 3.2.0.
