### ISSUE TITLE
bold+italic color doesn't work correctly in Reading mode

### ISSUE THREAD

**Issue by ShahriarKh** [damiankorcz/Prism-Theme#92]
Bold+Italic texts are shown the same color as the italic in Reading mode. Source and Live Preview modes are working fine.

**To Reproduce**
1. Set colors for bold, italic and bold+italic
2. Create a bold+italic text with ***
3. View the note in Reading mode

Reading:

![image](https://user-images.githubusercontent.com/31452340/201519968-b66366e2-a386-42a5-ba43-d68669ee0e5b.png)

---

Live Preview:

![image](https://user-images.githubusercontent.com/31452340/201520006-31f7d356-e407-4c80-9630-1dedb15c6e8f.png)

---

Source:

![image](https://user-images.githubusercontent.com/31452340/201519981-22484e3f-1a1a-4173-9680-6d2efdda9967.png)

**Setup Information**
 - Device Type: PC
 - Operating System: Windows 10
 - Prism version: 3.0.0
 - Color Schemes Used: Both
 - Obsidian Version: 1.0.3
 - Obsidian Installer Version: 0.15.8
 - Related Community plugins: 🤔

**Comment by damiankorcz** [comment]
Hi @ShahriarKh,
This is now fixed in 3.0.1. Thanks for reporting!

**Comment by ShahriarKh** [comment]
Hi @damiankorcz 
Thanks for the quick fix! 🔥
