### ISSUE TITLE
[Bug] Nested callouts render parent color

### ISSUE THREAD

**Issue by tauren** [damiankorcz/Prism-Theme#93]
**Describe the bug**
Nested callouts render in the same color as the parent callout, even if they are different types.

**To Reproduce**
Add the following to a note:
```
>[!WARNING]+ Parent Warning callout
>
> >[!SUCCESS]+ Child Success callout
> >Content
>
> >[!NOTE]+ Child Note callout
> >Content
```

This renders all callouts in orange.

**Expected behavior**
Should show an orange parent callout with nested green and grey callouts.

**Screenshots**
![image](https://user-images.githubusercontent.com/282084/201590327-3cc3b61b-a0c5-4205-bc09-075e80758698.png)

**Setup Information**
 - Device Type: Mac
 - Operating System: MacOS Monterey
 - Prism version: v3.0.1
 - Color Schemes Used: Raven Dark theme
 - Obsidian Version: v1.0.3
 - Obsidian Installer Version: 0.15.9
 - Related Community plugins: 

**Additional context**
Note that the nested callouts render correctly when the parent is type `NOTE`. And some other types render partially correct. But many combinations don't render correctly at all.

**Comment by damiankorcz** [comment]
Hi @tauren,
This issue should now be resolved in Prism 3.0.2.
