### ISSUE TITLE
[Bug] Cursor spacing is off when bullet has text and cursor is at beginning of line in live preview

### ISSUE THREAD

**Issue by mbentley** [damiankorcz/Prism-Theme#94]
**Describe the bug**
When you have a bulleted list, the cursor location appears further left than expected.  It looks like there is an extra space in front of the text.  This occurs in editing live preview mode.

**To Reproduce**
1. Create a bulleted list
2. Move the cursor to the beginning of the line (after the bullet itself)
3. See that it looks like there is a space but there isn't.

**Expected behavior**
I would expect that the cursor would be directly in front of the first character

**Screenshots**

![bullets](https://user-images.githubusercontent.com/414445/201653694-b5feec39-767b-4cde-8a47-a99b6df29654.gif)

**Setup Information**
 - Device Type: Mac
 - Operating System: happens on both macOS Ventura & Monterey
 - Prism version: Prism 3.0.1 (and earlier)
 - Color Schemes Used: Raven
 - Obsidian Version: v1.0.3
 - Obsidian Installer Version: v1.0.0
 - Related Community plugins: Bug happens with no plugins enabled as well as with.

**Additional context**

I've temporarily added a snippet to work around the issue:

```
.markdown-source-view.mod-cm6 :is(.cm-formatting-list-ul, .cm-formatting-list-ol) {
  padding-right: unset;
}
```

**Comment by damiankorcz** [comment]
Hi @mbentley,
This issue should now be resolved in Prism 3.0.2.
