### ISSUE TITLE
First line obscured when using the Tab Title Bar

### ISSUE THREAD

**Issue by BlownIntoSpace** [damiankorcz/Prism-Theme#98]
It seems to mostly affect tabs containing a plugin window, but, the first header line is always obscured behind the tab title bar. This doesn't happen on other themes i have tried.

Steps to recreate:
Open a plugin page (e.g. Advanced tables toolbar in this case)
Open it in the tab pane (i just drag and drop it there)

The toolbar is now completely obscured by the tab title bar. This happens with every plugin i have tried.

![image](https://user-images.githubusercontent.com/13012243/202314013-1caa3a0c-dfd6-41f6-a6af-061e21d5559e.png)

**Comment by damiankorcz** [comment]
Hi @BlownIntoSpace,
I'm aware of this issue and will look into mitigating it. In this specific case I'd expect the Advanced Tables to be used in the sidebar instead of the main workspace. In that case it should render correctly.

**Comment by damiankorcz** [comment]
Hi @BlownIntoSpace,
This issue should now be addressed in version 3.1.0.
