### ISSUE TITLE
[Bug]Selected text highlight not visible in dark mode

### ISSUE THREAD

**Issue by ZephiraZ** [damiankorcz/Prism-Theme#99]
[Please fill out the following sections as best you can to help diagnose the issue. Remove all `[ ]` bracket enclosed description/example elements including this one before submitting the bug.]

**Describe the bug**
When using Prism in dark mode, the highlight on selected text is not visible. This issue does not occur in light mode, with the default theme, or with other themes. No CSS snippets have been loaded, and the issue also occurs with all plugins disabled.

**To Reproduce**
1. Use any dark mode Prism preset.
2. Open a note containing text.
3. Select the text with Ctrl+A, Shift+Arrow Keys, or clicking and dragging around the text.
4. The selected text highlight is not visible.

**Expected behavior**
It is expected that a highlight will be visible around all selected text.

**Screenshots**
https://user-images.githubusercontent.com/102687150/202828297-54e4efce-5bee-4312-ab2f-7bdd3093cfe6.mp4

**Setup Information**
 - Device Type: Lenovo laptop
 - Operating System: Windows 10
 - Prism version: 3.0.3
 - Color Schemes Used: Raven, Mocha, Indigo, Pine
 - Obsidian Version: v1.0.3
 - Obsidian Installer Version: v0.15.9
 - Related Community plugins: Style Settings

**Additional context**
This issue was first observed after updating to 3.0.3. I have never used other CSS snippets, or other themes.

https://user-images.githubusercontent.com/102687150/202828297-54e4efce-5bee-4312-ab2f-7bdd3093cfe6.mp4

**Comment by damiankorcz** [comment]
Hi @ZephiraZ,
Thanks for reporting it here. I can replicate the issue. Looks like I've messed up with assigning the custom accent colour to the text highlight. Will look to fix it this weekend.

**Comment by damiankorcz** [comment]
Hi @ZephiraZ,
This should now be resolved in 3.0.4. Also, refer to the Important message in the changelog since I think it will apply in your case.
https://github.com/damiankorcz/Prism-Theme/releases/tag/3.0.4
